---
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Whether search/query results are allowed to match on multiple DNs,\
    \ or whether a single unique DN is expected for the result."
  name: "cas.consent.ldap.allow-multiple-dns"
  defaultValue: false
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Set if multiple Entries are allowed."
  name: "cas.consent.ldap.allow-multiple-entries"
  defaultValue: false
- required: true
  module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Base DN to use."
  name: "cas.consent.ldap.base-dn"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.util.List<java.lang.String>"
  description: "Indicate the collection of attributes that are to be tagged and processed\
    \ as binary attributes by the underlying search resolver."
  name: "cas.consent.ldap.binary-attributes"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "The bind credential to use when connecting to LDAP."
  name: "cas.consent.ldap.bind-credential"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "The bind DN to use when connecting to LDAP. LDAP connection configuration\
    \ injected into the LDAP connection pool can be initialized with the following\
    \ parameters: <ul> <li>{@code bindDn/bindCredential} provided - Use the provided\
    \ credentials to bind when initializing connections.</li> <li>{@code bindDn/bindCredential}\
    \  set to {@code *} - Use a fast-bind strategy to initialize the pool.</li> <li>{@code\
    \ bindDn/bindCredential}  set to blank - Skip connection initializing; perform\
    \ operations anonymously. </li> <li>SASL mechanism provided - Use the given SASL\
    \ mechanism to bind when initializing connections. </li> </ul>"
  name: "cas.consent.ldap.bind-dn"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "The length of time the pool will block. By default the pool will block\
    \ indefinitely and there is no guarantee that waiting threads will be serviced\
    \ in the order in which they made their request. This option should be used with\
    \ a blocking connection pool when you need to control the exact number of connections\
    \ that can be created"
  name: "cas.consent.ldap.block-wait-time"
  defaultValue: "PT3S"
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Sets the maximum amount of time that connects will block."
  name: "cas.consent.ldap.connect-timeout"
  defaultValue: "PT5S"
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "If multiple URLs are provided as the ldapURL this describes how each\
    \ URL will be processed. <ul> <li>{@code ACTIVE_PASSIVE} First LDAP will be used\
    \ for every request unless it fails and then the next shall be used.</li> <li>{@code\
    \ ROUND_ROBIN} For each new connection the next url in the list will be used.</li>\
    \ <li>{@code RANDOM} For each new connection a random LDAP url will be selected.</li>\
    \ <li>{@code DNS_SRV} LDAP urls based on DNS SRV records of the configured/given\
    \ LDAP url will be used. </li> </ul>"
  name: "cas.consent.ldap.connection-strategy"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Name of LDAP attribute that holds consent decisions as JSON."
  name: "cas.consent.ldap.consent-attribute-name"
  defaultValue: "casConsentDecision"
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Whether to use a pooled connection factory in components."
  name: "cas.consent.ldap.disable-pooling"
  defaultValue: false
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Attempt to populate the connection pool early on startup and fail\
    \ quickly if something goes wrong."
  name: "cas.consent.ldap.fail-fast"
  defaultValue: true
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Set if search referrals should be followed."
  name: "cas.consent.ldap.follow-referrals"
  defaultValue: true
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "org.apereo.cas.configuration.model.support.ldap.AbstractLdapProperties$LdapHostnameVerifierOptions"
  description: "Hostname verification options. Accepted values are {@link LdapHostnameVerifierOptions#DEFAULT}\
    \ and {@link LdapHostnameVerifierOptions#ANY}.DEFAULT:Default option, forcing\
    \ verification..ANY:Skip hostname verification and allow all.."
  name: "cas.consent.ldap.hostname-verifier"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Removes connections from the pool based on how long they have been\
    \ idle in the available queue. Prunes connections that have been idle for more\
    \ than the indicated amount."
  name: "cas.consent.ldap.idle-time"
  defaultValue: "PT10M"
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Path to the keystore used for SSL connections. Typically contains\
    \ SSL certificates for the LDAP server."
  name: "cas.consent.ldap.keystore"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Keystore password."
  name: "cas.consent.ldap.keystore-password"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "The type of keystore. {@code PKCS12} or {@code JKS}. If left blank,\
    \ defaults to the default keystore type indicated by the underlying Java platform."
  name: "cas.consent.ldap.keystore-type"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "The LDAP url to the server. More than one may be specified, separated\
    \ by space and/or comma."
  name: "cas.consent.ldap.ldap-url"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Integer"
  description: "Maximum LDAP connection pool size which the pool can use to grow."
  name: "cas.consent.ldap.max-pool-size"
  defaultValue: 10
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Integer"
  description: "Minimum LDAP connection pool size. Size the pool should be initialized\
    \ to and pruned to"
  name: "cas.consent.ldap.min-pool-size"
  defaultValue: 3
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Name of the LDAP handler."
  name: "cas.consent.ldap.name"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Integer"
  description: "Request that the server return results in batches of a specific size.\
    \ See <a href=\"http://www.ietf.org/rfc/rfc2696.txt\">RFC 2696</a>. This control\
    \ is often used to work around server result size limits. A negative/zero value\
    \ disables paged requests."
  name: "cas.consent.ldap.page-size"
  defaultValue: 0
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "You may receive unexpected LDAP failures, when CAS is configured to\
    \ authenticate using DIRECT or AUTHENTICATED types and LDAP is locked down to\
    \ not allow anonymous binds/searches. Every second attempt with a given LDAP connection\
    \ from the pool would fail if it was on the same connection as a failed login\
    \ attempt, and the regular connection validator would similarly fail. When a connection\
    \ is returned back to a pool, it still may contain the principal and credentials\
    \ from the previous attempt. Before the next bind attempt using that connection,\
    \ the validator tries to validate the connection again but fails because it’s\
    \ no longer trying with the configured bind credentials but with whatever user\
    \ DN was used in the previous step. Given the validation failure, the connection\
    \ is closed and CAS would deny access by default. Passivators attempt to reconnect\
    \ to LDAP with the configured bind credentials, effectively resetting the connection\
    \ to what it should be after each bind request."
  name: "cas.consent.ldap.pool-passivator"
  defaultValue: "BIND"
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Removes connections from the pool based on how long they have been\
    \ idle in the available queue. Run the pruning process at the indicated interval."
  name: "cas.consent.ldap.prune-period"
  defaultValue: "PT2H"
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Duration of time to wait for responses."
  name: "cas.consent.ldap.response-timeout"
  defaultValue: "PT5S"
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "SASL authorization id."
  name: "cas.consent.ldap.sasl-authorization-id"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "The SASL mechanism."
  name: "cas.consent.ldap.sasl-mechanism"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "SASL mutual auth is enabled?"
  name: "cas.consent.ldap.sasl-mutual-auth"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "SASL quality of protected."
  name: "cas.consent.ldap.sasl-quality-of-protection"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "The SASL realm."
  name: "cas.consent.ldap.sasl-realm"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "SASL security strength."
  name: "cas.consent.ldap.sasl-security-strength"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.util.List<org.apereo.cas.configuration.model.support.ldap.LdapSearchEntryHandlersProperties>"
  description: "Search handlers."
  name: "cas.consent.ldap.search-entry-handlers"
  defaultValue: ""
- required: true
  module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "User filter to use for searching. Syntax is {@code cn={user}} or {@code\
    \ cn={0}}. You may also provide an external groovy script in the syntax of {@code\
    \ file:/path/to/GroovyScript.groovy} to fully build the final filter template\
    \ dynamically."
  name: "cas.consent.ldap.search-filter"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Whether subtree searching is allowed."
  name: "cas.consent.ldap.subtree-search"
  defaultValue: true
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Path of the trust certificates to use for the SSL connection. Ignores\
    \ keystore-related settings when activated and used."
  name: "cas.consent.ldap.trust-certificates"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Trust Manager options. Accepted values are {@link LdapTrustManagerOptions#ANY},\
    \ {@link LdapTrustManagerOptions#DEFAULT}."
  name: "cas.consent.ldap.trust-manager"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Path to the keystore used to determine which certificates or certificate\
    \ authorities should be trusted. Used when connecting to an LDAP server via LDAPS\
    \ or startTLS connection. If left blank, the default truststore for the Java runtime\
    \ is used."
  name: "cas.consent.ldap.trust-store"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Password needed to open the truststore."
  name: "cas.consent.ldap.trust-store-password"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "The type of trust keystore that determines which certificates or certificate\
    \ authorities are trusted. Types depend on underlying java platform, typically\
    \ {@code PKCS12} or {@code JKS}. If left blank, defaults to the default keystore\
    \ type indicated by the underlying Java platform."
  name: "cas.consent.ldap.trust-store-type"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "org.apereo.cas.configuration.model.support.ldap.AbstractLdapProperties$LdapType"
  description: "Type of LDAP directory.GENERIC:Generic ldap type (OpenLDAP, 389ds,\
    \ etc)..AD:Active directory..FreeIPA:FreeIPA directory..EDirectory:EDirectory.."
  name: "cas.consent.ldap.type"
  defaultValue: ""
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Whether TLS should be used and enabled when establishing the connection."
  name: "cas.consent.ldap.use-start-tls"
  defaultValue: false
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Whether connections should be validated when loaned out from the pool."
  name: "cas.consent.ldap.validate-on-checkout"
  defaultValue: true
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Period at which pool should be validated."
  name: "cas.consent.ldap.validate-period"
  defaultValue: "PT5M"
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.Boolean"
  description: "Whether connections should be validated periodically when the pool\
    \ is idle."
  name: "cas.consent.ldap.validate-periodically"
  defaultValue: true
- module: "cas-server-consent-ldap"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties.Ldap"
  type: "java.lang.String"
  description: "Period at which validation operations may time out."
  name: "cas.consent.ldap.validate-timeout"
  defaultValue: "PT5S"
