---
- module: "cas-server-support-syncope-authentication"
  owner: "org.apereo.cas.configuration.model.support.syncope.SyncopeAuthenticationProperties"
  type: "java.lang.String"
  description: "A number of authentication handlers are allowed to determine whether\
    \ they can operate on the provided credential and as such lend themselves to be\
    \ tried and tested during the authentication handler selection phase. The credential\
    \ criteria may be one of the following options:<ul> <li>1) A regular expression\
    \ pattern that is tested against the credential identifier.</li> <li>2) A fully\
    \ qualified class name of your own design that implements {@code Predicate}.</li>\
    \ <li>3) Path to an external Groovy script that implements the same interface.</li>\
    \ </ul>"
  name: "cas.authn.syncope.credential-criteria"
  defaultValue: ""
- required: true
  module: "cas-server-support-syncope-authentication"
  owner: "org.apereo.cas.configuration.model.support.syncope.SyncopeAuthenticationProperties"
  type: "java.lang.String"
  description: "Syncope domain used for authentication, etc."
  name: "cas.authn.syncope.domain"
  defaultValue: "Master"
- module: "cas-server-support-syncope-authentication"
  owner: "org.apereo.cas.configuration.model.support.syncope.SyncopeAuthenticationProperties"
  type: "java.lang.String"
  description: "Name of the authentication handler."
  name: "cas.authn.syncope.name"
  defaultValue: ""
- required: true
  module: "cas-server-support-syncope-authentication"
  owner: "org.apereo.cas.configuration.model.support.syncope.SyncopeAuthenticationProperties"
  type: "java.lang.String"
  description: "Syncope instance URL primary used for REST."
  name: "cas.authn.syncope.url"
  defaultValue: ""
