---
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines an oauth token for the kubernetes client to access the kubernetes\
    \ REST API. Defaults to reading the token from the auto-injected file at: {@code\
    \ /var/run/secrets/kubernetes.io/serviceaccount/token}."
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.api-token"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines an alternative address for the kubernetes master. Defaults\
    \ to: {@code https://kubernetes.default.svc}"
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.kubernetes-master"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the namespace of the application POD through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.namespace"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.Boolean"
  description: "Defines if not ready addresses should be evaluated to be discovered\
    \ on startup."
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.resolve-not-ready-addresses"
  defaultValue: false
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the DNS service lookup domain. This is defined as something\
    \ similar to {@code my-svc.my-namespace.svc.cluster.local}."
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.service-dns"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.Integer"
  description: "Defines the DNS service lookup timeout in seconds. Defaults to 5 secs."
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.service-dns-timeout"
  defaultValue: -1
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service label to lookup through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.service-label-name"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service label value to lookup through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.service-label-value"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service name of the POD to lookup through the Service\
    \ Discovery REST API of Kubernetes."
  name: "cas.authn.throttle.hazelcast.cluster.discovery.kubernetes.service-name"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines an oauth token for the kubernetes client to access the kubernetes\
    \ REST API. Defaults to reading the token from the auto-injected file at: {@code\
    \ /var/run/secrets/kubernetes.io/serviceaccount/token}."
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.api-token"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines an alternative address for the kubernetes master. Defaults\
    \ to: {@code https://kubernetes.default.svc}"
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.kubernetes-master"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the namespace of the application POD through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.namespace"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.Boolean"
  description: "Defines if not ready addresses should be evaluated to be discovered\
    \ on startup."
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.resolve-not-ready-addresses"
  defaultValue: false
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the DNS service lookup domain. This is defined as something\
    \ similar to {@code my-svc.my-namespace.svc.cluster.local}."
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.service-dns"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.Integer"
  description: "Defines the DNS service lookup timeout in seconds. Defaults to 5 secs."
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.service-dns-timeout"
  defaultValue: -1
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service label to lookup through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.service-label-name"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service label value to lookup through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.service-label-value"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service name of the POD to lookup through the Service\
    \ Discovery REST API of Kubernetes."
  name: "cas.service-registry.stream.hazelcast.config.cluster.discovery.kubernetes.service-name"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines an oauth token for the kubernetes client to access the kubernetes\
    \ REST API. Defaults to reading the token from the auto-injected file at: {@code\
    \ /var/run/secrets/kubernetes.io/serviceaccount/token}."
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.api-token"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines an alternative address for the kubernetes master. Defaults\
    \ to: {@code https://kubernetes.default.svc}"
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.kubernetes-master"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the namespace of the application POD through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.namespace"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.Boolean"
  description: "Defines if not ready addresses should be evaluated to be discovered\
    \ on startup."
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.resolve-not-ready-addresses"
  defaultValue: false
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the DNS service lookup domain. This is defined as something\
    \ similar to {@code my-svc.my-namespace.svc.cluster.local}."
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.service-dns"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.Integer"
  description: "Defines the DNS service lookup timeout in seconds. Defaults to 5 secs."
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.service-dns-timeout"
  defaultValue: -1
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service label to lookup through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.service-label-name"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service label value to lookup through the Service Discovery\
    \ REST API of Kubernetes."
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.service-label-value"
  defaultValue: ""
- module: "cas-server-support-hazelcast-discovery-kubernetes"
  owner: "org.apereo.cas.configuration.model.support.hazelcast.discovery.HazelcastKubernetesDiscoveryProperties"
  type: "java.lang.String"
  description: "Defines the service name of the POD to lookup through the Service\
    \ Discovery REST API of Kubernetes."
  name: "cas.ticket.registry.hazelcast.cluster.discovery.kubernetes.service-name"
  defaultValue: ""
