---
- required: true
  module: "cas-server-support-pac4j"
  owner: "org.apereo.cas.configuration.model.support.pac4j.Pac4jDelegatedAuthenticationProvisioningProperties.Groovy"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  name: "cas.authn.pac4j.provisioning.groovy.location"
  defaultValue: ""
- module: "cas-server-support-pac4j"
  owner: "org.apereo.cas.configuration.model.support.pac4j.Pac4jDelegatedAuthenticationProvisioningProperties.Rest"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ password for authentication."
  name: "cas.authn.pac4j.provisioning.rest.basic-auth-password"
  defaultValue: ""
- module: "cas-server-support-pac4j"
  owner: "org.apereo.cas.configuration.model.support.pac4j.Pac4jDelegatedAuthenticationProvisioningProperties.Rest"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ username for authentication."
  name: "cas.authn.pac4j.provisioning.rest.basic-auth-username"
  defaultValue: ""
- module: "cas-server-support-pac4j"
  owner: "org.apereo.cas.configuration.model.support.pac4j.Pac4jDelegatedAuthenticationProvisioningProperties.Rest"
  type: "java.lang.String"
  description: "HTTP method to use when contacting the rest endpoint. Examples include\
    \ {@code GET, POST}, etc."
  name: "cas.authn.pac4j.provisioning.rest.method"
  defaultValue: "GET"
- required: true
  module: "cas-server-support-pac4j"
  owner: "org.apereo.cas.configuration.model.support.pac4j.Pac4jDelegatedAuthenticationProvisioningProperties.Rest"
  type: "java.lang.String"
  description: "The endpoint URL to contact and retrieve attributes."
  name: "cas.authn.pac4j.provisioning.rest.url"
  defaultValue: ""
