---
- module: "cas-server-support-consent-webflow"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties"
  type: "java.lang.Boolean"
  description: "Whether consent functionality should be globally applicapable to all\
    \ applications and requests."
  name: "cas.consent.active"
  defaultValue: true
- module: "cas-server-support-consent-webflow"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties"
  type: "java.lang.Boolean"
  description: "Whether consent functionality should be enabled."
  name: "cas.consent.enabled"
  defaultValue: true
- module: "cas-server-support-consent-webflow"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties"
  type: "java.lang.Long"
  description: "Global reminder time unit, to reconfirm consent in cases no changes\
    \ are detected."
  name: "cas.consent.reminder"
  defaultValue: 30
- module: "cas-server-support-consent-webflow"
  owner: "org.apereo.cas.configuration.model.support.consent.ConsentProperties"
  type: "java.time.temporal.ChronoUnit"
  description: "Global reminder time unit of measure, to reconfirm consent in cases\
    \ no changes are detected."
  name: "cas.consent.reminder-time-unit"
  defaultValue: ""
