---
- method: "GET"
  path: "authenticationPolicies/${name}"
  signature: "RegisteredAuthenticationPoliciesEndpoint$AuthenticationPolicyDetails\
    \ org.apereo.cas.web.report.RegisteredAuthenticationPoliciesEndpoint.fetchPolicy(java.lang.String)"
  returnType: "AuthenticationPolicyDetails"
  summary: "Get available authentication policy by name."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "name"
  produces:
  - "application/vnd.spring-boot.actuator.v2+json"
  - "application/vnd.cas.services+yaml"
  - "application/json"
- method: "GET"
  path: "authenticationPolicies"
  signature: "RegisteredAuthenticationPoliciesEndpoint$AuthenticationPolicyDetails>\
    \ org.apereo.cas.web.report.RegisteredAuthenticationPoliciesEndpoint.handle()"
  returnType: "Collection"
  summary: "Get available authentication policies."
  produces:
  - "application/vnd.spring-boot.actuator.v2+json"
  - "application/vnd.cas.services+yaml"
  - "application/json"
