---
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Client execution timeout."
  name: "cas.spring.cloud.aws.secrets-manager.client-execution-timeout"
  defaultValue: "10000"
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Connection timeout."
  name: "cas.spring.cloud.aws.secrets-manager.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  name: "cas.spring.cloud.aws.secrets-manager.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  name: "cas.spring.cloud.aws.secrets-manager.credential-secret-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  name: "cas.spring.cloud.aws.secrets-manager.endpoint"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Local address."
  name: "cas.spring.cloud.aws.secrets-manager.local-address"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  name: "cas.spring.cloud.aws.secrets-manager.max-connections"
  defaultValue: 10
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Profile name to use."
  name: "cas.spring.cloud.aws.secrets-manager.profile-name"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Profile path."
  name: "cas.spring.cloud.aws.secrets-manager.profile-path"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  name: "cas.spring.cloud.aws.secrets-manager.proxy-host"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  name: "cas.spring.cloud.aws.secrets-manager.proxy-password"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  name: "cas.spring.cloud.aws.secrets-manager.proxy-username"
  defaultValue: ""
- required: true
  module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "AWS region used."
  name: "cas.spring.cloud.aws.secrets-manager.region"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  name: "cas.spring.cloud.aws.secrets-manager.retry-mode"
  defaultValue: "STANDARD"
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.String"
  description: "Socket timeout."
  name: "cas.spring.cloud.aws.secrets-manager.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-configuration-cloud-aws-secretsmanager"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonSecretsManager"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  name: "cas.spring.cloud.aws.secrets-manager.use-reaper"
  defaultValue: false
