---
- method: "GET"
  path: "samlIdPRegisteredServiceMetadataCache"
  signature: "SamlRegisteredServiceCachedMetadataEndpoint.getCachedMetadataObject(java.lang.String,java.lang.String)"
  returnType: "Map"
  summary: "Get SAML2 cached metadata."
  parameters:
  - required: true
    type: "String"
    selector: false
    name: "serviceId"
  - required: false
    type: "String"
    selector: false
    name: "entityId"
- method: "DELETE"
  path: "samlIdPRegisteredServiceMetadataCache"
  signature: "SamlRegisteredServiceCachedMetadataEndpoint.invalidate(java.lang.String)"
  returnType: "void"
  summary: "Invalidate SAML2 metadata cache using an entity id."
  parameters:
  - required: false
    type: "String"
    selector: false
    name: "serviceId"
