---
- method: "GET"
  path: "samlIdPRegisteredServiceMetadataCache"
  name: "samlIdPRegisteredServiceMetadataCache"
  endpointType: "Endpoint"
  signature: "SamlRegisteredServiceCachedMetadataEndpoint.getCachedMetadataObject(java.lang.String,java.lang.String)"
  owner: "org.apereo.cas.support.saml.web.idp.metadata.SamlRegisteredServiceCachedMetadataEndpoint"
  returnType: "Map"
  casEndpoint: true
  summary: "Get SAML2 cached metadata."
  parameters:
  - required: true
    type: "String"
    selector: false
    name: "serviceId"
  - required: false
    type: "String"
    selector: false
    name: "entityId"
- method: "DELETE"
  path: "samlIdPRegisteredServiceMetadataCache"
  name: "samlIdPRegisteredServiceMetadataCache"
  endpointType: "Endpoint"
  signature: "SamlRegisteredServiceCachedMetadataEndpoint.invalidate(java.lang.String)"
  owner: "org.apereo.cas.support.saml.web.idp.metadata.SamlRegisteredServiceCachedMetadataEndpoint"
  casEndpoint: true
  summary: "Invalidate SAML2 metadata cache using an entity id."
  parameters:
  - required: false
    type: "String"
    selector: false
    name: "serviceId"
