---
- method: "POST"
  path: "pause"
  signature: "PauseEndpoint.pause()"
  owner: "org.springframework.cloud.context.restart.RestartEndpoint$PauseEndpoint"
  returnType: "Boolean"
  casEndpoint: false
