---
- required: true
  module: "cas-server-support-geolocation-maxmind"
  owner: "org.apereo.cas.configuration.model.support.geo.maxmind.MaxmindProperties"
  type: "org.springframework.core.io.Resource"
  description: "Path to the location of the database file containing cities."
  shortDescription: "Path to the location of the database file containing cities."
  name: "cas.maxmind.city-database"
  defaultValue: ""
- required: true
  module: "cas-server-support-geolocation-maxmind"
  owner: "org.apereo.cas.configuration.model.support.geo.maxmind.MaxmindProperties"
  type: "org.springframework.core.io.Resource"
  description: "Path to the location of the database file containing countries."
  shortDescription: "Path to the location of the database file containing countries."
  name: "cas.maxmind.country-database"
  defaultValue: ""
- module: "cas-server-support-geolocation-maxmind"
  owner: "org.apereo.cas.configuration.model.support.geo.maxmind.MaxmindProperties"
  type: "java.lang.String"
  description: "The access key for ip-stack used to look up ip addresses for geo locations.\
    \ See <a href=\"http://ipstack.com\">this link</a> for more info."
  shortDescription: "The access key for ip-stack used to look up ip addresses for\
    \ geo locations."
  name: "cas.maxmind.ip-stack-api-access-key"
  defaultValue: ""
