---
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.GrouperPrincipalAttributesProperties"
  type: "java.lang.Boolean"
  description: "Enable the attribute repository source."
  name: "cas.authn.attribute-repository.grouper.enabled"
  defaultValue: false
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.GrouperPrincipalAttributesProperties"
  type: "java.lang.String"
  description: "A value can be assigned to this field to uniquely identify this resolver."
  name: "cas.authn.attribute-repository.grouper.id"
  defaultValue: ""
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.GrouperPrincipalAttributesProperties"
  type: "java.lang.Integer"
  description: "The order of this attribute repository in the chain of repositories.\
    \ Can be used to explicitly position this source in chain and affects merging\
    \ strategies."
  name: "cas.authn.attribute-repository.grouper.order"
  defaultValue: 0
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.ScriptedPrincipalAttributesProperties"
  type: "boolean"
  description: "Whether attribute repository should consider the underlying\nattribute\
    \ names in a case-insensitive manner."
  name: "cas.authn.attribute-repository.script[].case-insensitive"
  defaultValue: ""
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.ScriptedPrincipalAttributesProperties"
  type: "java.lang.String"
  description: "Script engine name, e.g. groovy, js, python, etc.\nRequired if CAS\
    \ can't determine based on extension.\nThe file extension of the resource will\
    \ be used to determine the engineName if not specified.\nEngines must be on the\
    \ classpath in order for the engineName to be determined automatically.\nThe first\
    \ engine found claiming to support the extension of the file specified will be\
    \ used."
  name: "cas.authn.attribute-repository.script[].engine-name"
  defaultValue: ""
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.ScriptedPrincipalAttributesProperties"
  type: "java.lang.String"
  description: "A value can be assigned to this field to uniquely identify this resolver."
  name: "cas.authn.attribute-repository.script[].id"
  defaultValue: ""
- required: true
  module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.ScriptedPrincipalAttributesProperties"
  type: "Resource"
  description: "The location of the resource. Resources can be URLS, or\nfiles found\
    \ either on the classpath or outside somewhere\nin the file system."
  name: "cas.authn.attribute-repository.script[].location"
  defaultValue: ""
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.ScriptedPrincipalAttributesProperties"
  type: "int"
  description: "The order of this attribute repository in the chain of repositories.\n\
    Can be used to explicitly position this source in chain and affects\nmerging strategies."
  name: "cas.authn.attribute-repository.script[].order"
  defaultValue: ""
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.StubPrincipalAttributesProperties"
  type: "java.util.Map<java.lang.String,java.lang.String>"
  description: "Static attributes that need to be mapped to a hardcoded value belong\
    \ here. The structure follows a key-value pair where key is the attribute name\
    \ and value is the attribute value. The key is the attribute fetched from the\
    \ source and the value is the attribute name CAS should use for virtual renames."
  name: "cas.authn.attribute-repository.stub.attributes"
  defaultValue: ""
- module: "cas-server-support-person-directory"
  owner: "org.apereo.cas.configuration.model.core.authentication.StubPrincipalAttributesProperties"
  type: "java.lang.String"
  description: "A value can be assigned to this field to uniquely identify this resolver."
  name: "cas.authn.attribute-repository.stub.id"
  defaultValue: ""
