---
- module: "cas-server-support-gauth-rest"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ password for authentication."
  name: "cas.authn.mfa.gauth.rest.basic-auth-password"
  defaultValue: ""
- module: "cas-server-support-gauth-rest"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ username for authentication."
  name: "cas.authn.mfa.gauth.rest.basic-auth-username"
  defaultValue: ""
- required: true
  module: "cas-server-support-gauth-rest"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "Endpoint url of the REST resource used for tokens that are kept to\
    \ prevent replay attacks."
  name: "cas.authn.mfa.gauth.rest.token-url"
  defaultValue: ""
- required: true
  module: "cas-server-support-gauth-rest"
  owner: "org.apereo.cas.configuration.model.support.mfa.gauth.RestfulGoogleAuthenticatorMultifactorProperties"
  type: "java.lang.String"
  description: "The endpoint URL to contact and retrieve attributes."
  name: "cas.authn.mfa.gauth.rest.url"
  defaultValue: ""
