---
- method: "GET"
  path: "loggingConfig"
  signature: "LoggingConfigurationEndpoint.configuration()"
  returnType: "Map"
  summary: "Get logging configuration report."
- method: "POST"
  path: "loggingConfig/${loggerName}"
  signature: "LoggingConfigurationEndpoint.updateLoggerLevel(java.lang.String,java.lang.String,boolean)"
  returnType: "void"
  summary: "Update logger level for a logger name."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "loggerName"
  - required: true
    type: "String"
    selector: false
    name: "loggerLevel"
  - required: true
    type: "boolean"
    selector: false
    name: "additive"
