---
- method: "GET"
  path: "duoPing"
  signature: "DuoSecurityPingEndpoint.pingDuo(java.lang.String)"
  returnType: "Map"
  summary: "Ping Duo Security given the provider id."
  parameters:
  - required: false
    type: "String"
    selector: false
    name: "providerId"
  produces:
  - "application/json"
