---
- method: "GET"
  path: "duoPing"
  name: "duoPing"
  endpointType: "Endpoint"
  signature: "DuoSecurityPingEndpoint.pingDuo(java.lang.String)"
  owner: "org.apereo.cas.adaptors.duo.web.DuoSecurityPingEndpoint"
  returnType: "Map"
  casEndpoint: true
  summary: "Ping Duo Security given the provider id."
  parameters:
  - required: false
    type: "String"
    selector: false
    name: "providerId"
  produces:
  - "application/json"
