---
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "Attributes to fetch from CouchDb."
  name: "cas.authn.couch-db.attributes"
  defaultValue: ""
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Boolean"
  description: "Use a local cache to reduce fetches.."
  name: "cas.authn.couch-db.caching"
  defaultValue: false
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Boolean"
  description: "Remove idle connections from pool."
  name: "cas.authn.couch-db.cleanup-idle-connections"
  defaultValue: true
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Integer"
  description: "TCP connection timeout."
  name: "cas.authn.couch-db.connection-timeout"
  defaultValue: 1000
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Boolean"
  description: "Create the database if it doesn't exist."
  name: "cas.authn.couch-db.create-if-not-exists"
  defaultValue: true
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "Database name. Defaults to +serviceRegistry+ and +ticketRegistry+\
    \ for the service and ticket registries, respectively."
  name: "cas.authn.couch-db.db-name"
  defaultValue: ""
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Boolean"
  description: "Use TLS. Only needed if not specified by URL."
  name: "cas.authn.couch-db.enable-ssl"
  defaultValue: false
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Max entries in local cache."
  name: "cas.authn.couch-db.max-cache-entries"
  defaultValue: 1000
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Maximum connections to CouchDB."
  name: "cas.authn.couch-db.max-connections"
  defaultValue: 20
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Largest allowable serialized object."
  name: "cas.authn.couch-db.max-object-size-bytes"
  defaultValue: 8192
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  name: "cas.authn.couch-db.name"
  defaultValue: ""
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Order of authentication handler in chain."
  name: "cas.authn.couch-db.order"
  defaultValue: ""
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "Password for connection."
  name: "cas.authn.couch-db.password"
  defaultValue: ""
- required: true
  module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "Password attribute to fetch and compare against credential."
  name: "cas.authn.couch-db.password-attribute"
  defaultValue: "password"
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "Proxy host."
  name: "cas.authn.couch-db.proxy-host"
  defaultValue: ""
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Integer"
  description: "proxy port."
  name: "cas.authn.couch-db.proxy-port"
  defaultValue: -1
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Boolean"
  description: "Relax TLS settings–like certificate verification."
  name: "cas.authn.couch-db.relaxed-ssl-settings"
  defaultValue: false
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Retries for update conflicts."
  name: "cas.authn.couch-db.retries"
  defaultValue: 5
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Socket idle timeout."
  name: "cas.authn.couch-db.socket-timeout"
  defaultValue: 10000
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "Connection url."
  name: "cas.authn.couch-db.url"
  defaultValue: "http://localhost:5984"
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.Boolean"
  description: "Expect HTTP 100 Continue during connection."
  name: "cas.authn.couch-db.use-expect-continue"
  defaultValue: true
- module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "Username for connection."
  name: "cas.authn.couch-db.username"
  defaultValue: ""
- required: true
  module: "cas-server-support-couchdb-authentication"
  owner: "org.apereo.cas.configuration.model.support.couchdb.authentication.CouchDbAuthenticationProperties"
  type: "java.lang.String"
  description: "Username attribute to fetch and compare against credential."
  name: "cas.authn.couch-db.username-attribute"
  defaultValue: "username"
