---
- module: "cas-server-support-trusted-rest"
  owner: "org.apereo.cas.configuration.model.support.mfa.trusteddevice.RestfulTrustedDevicesMultifactorProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ password for authentication."
  name: "cas.authn.mfa.trusted.rest.basic-auth-password"
  defaultValue: ""
- module: "cas-server-support-trusted-rest"
  owner: "org.apereo.cas.configuration.model.support.mfa.trusteddevice.RestfulTrustedDevicesMultifactorProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ username for authentication."
  name: "cas.authn.mfa.trusted.rest.basic-auth-username"
  defaultValue: ""
- module: "cas-server-support-trusted-rest"
  owner: "org.apereo.cas.configuration.model.support.mfa.trusteddevice.RestfulTrustedDevicesMultifactorProperties"
  type: "java.lang.String"
  description: "HTTP method to use when contacting the rest endpoint. Examples include\
    \ {@code GET, POST}, etc."
  name: "cas.authn.mfa.trusted.rest.method"
  defaultValue: "GET"
- required: true
  module: "cas-server-support-trusted-rest"
  owner: "org.apereo.cas.configuration.model.support.mfa.trusteddevice.RestfulTrustedDevicesMultifactorProperties"
  type: "java.lang.String"
  description: "The endpoint URL to contact and retrieve attributes."
  name: "cas.authn.mfa.trusted.rest.url"
  defaultValue: ""
