---
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.lang.Long"
  description: "Expire and forget device registration records after this period."
  name: "cas.authn.mfa.u2f.expire-devices"
  defaultValue: 30
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.util.concurrent.TimeUnit"
  description: "Device registration record expiration time unit."
  name: "cas.authn.mfa.u2f.expire-devices-time-unit"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.lang.Long"
  description: "Expire and forget device registration requests after this period."
  name: "cas.authn.mfa.u2f.expire-registrations"
  defaultValue: 30
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.util.concurrent.TimeUnit"
  description: "Device registration requests expiration time unit."
  name: "cas.authn.mfa.u2f.expire-registrations-time-unit"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.lang.String"
  description: "The failure mode policy for this MFA provider."
  name: "cas.authn.mfa.u2f.failure-mode"
  defaultValue: "UNDEFINED"
- required: true
  module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FGroovyMultifactorProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  name: "cas.authn.mfa.u2f.groovy.location"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.lang.String"
  description: "The identifier for the multifactor provider. In most cases, this need\
    \ not be configured explicitly, unless multiple instances of the same provider\
    \ type are configured in CAS."
  name: "cas.authn.mfa.u2f.id"
  defaultValue: ""
- required: true
  module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FJsonMultifactorProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  name: "cas.authn.mfa.u2f.json.location"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler used to verify credentials\
    \ in MFA."
  name: "cas.authn.mfa.u2f.name"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.lang.Integer"
  description: "The order of the authentication handler in the chain."
  name: "cas.authn.mfa.u2f.order"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.lang.Integer"
  description: "At times, CAS needs to determine the correct provider when step-up\
    \ authentication is required. Consider for a moment that CAS already has established\
    \ an SSO session with/without a provider and has reached a level of authentication.\
    \ Another incoming request attempts to exercise that SSO session with a different\
    \ and often competing authentication requirement that may differ from the authentication\
    \ level CAS has already established. Concretely, examples may be: <ul> <li>CAS\
    \ has achieved an SSO session, but a separate request now requires step-up authentication\
    \ with DuoSecurity.</li> <li>CAS has achieved an SSO session with an authentication\
    \ level satisfied by DuoSecurity, but a separate request now requires step-up\
    \ authentication with YubiKey. </li> </ul> In certain scenarios, CAS will attempt\
    \ to rank authentication levels and compare them with each other. If CAS already\
    \ has achieved a level that is higher than what the incoming request requires,\
    \ no step-up authentication will be performed. If the opposite is true, CAS will\
    \ route the authentication flow to the required authentication level and upon\
    \ success, will adjust the SSO session with the new higher authentication level\
    \ now satisfied. <p> Ranking of authentication methods is done per provider via\
    \ specific properties for each. Note that the higher the rank value is, the higher\
    \ on the security scale it remains. A provider that ranks higher with a larger\
    \ weight value trumps and override others with a lower value. </p>"
  name: "cas.authn.mfa.u2f.rank"
  defaultValue: 0
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FRestfulMultifactorProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ password for authentication."
  name: "cas.authn.mfa.u2f.rest.basic-auth-password"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FRestfulMultifactorProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ username for authentication."
  name: "cas.authn.mfa.u2f.rest.basic-auth-username"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FRestfulMultifactorProperties"
  type: "java.lang.String"
  description: "HTTP method to use when contacting the rest endpoint. Examples include\
    \ {@code GET, POST}, etc."
  name: "cas.authn.mfa.u2f.rest.method"
  defaultValue: "GET"
- required: true
  module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FRestfulMultifactorProperties"
  type: "java.lang.String"
  description: "The endpoint URL to contact and retrieve attributes."
  name: "cas.authn.mfa.u2f.rest.url"
  defaultValue: ""
- module: "cas-server-support-u2f"
  owner: "org.apereo.cas.configuration.model.support.mfa.u2f.U2FMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Indicates whether this provider should support trusted devices."
  name: "cas.authn.mfa.u2f.trusted-device-enabled"
  defaultValue: false
