---
- method: "GET"
  path: "serviceregistry"
  signature: "ServiceRegistryEndpoint.getStatus()"
  owner: "org.springframework.cloud.client.serviceregistry.endpoint.ServiceRegistryEndpoint"
  returnType: "ResponseEntity"
  casEndpoint: false
- method: "POST"
  path: "serviceregistry"
  signature: "ServiceRegistryEndpoint.setStatus(java.lang.String)"
  owner: "org.springframework.cloud.client.serviceregistry.endpoint.ServiceRegistryEndpoint"
  returnType: "ResponseEntity"
  casEndpoint: false
  parameters:
  - required: true
    type: "String"
    selector: false
