---
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Client execution timeout."
  name: "cas.authn.cognito.client-execution-timeout"
  defaultValue: "10000"
- required: true
  module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "The application client id, created in Cognito without a secret key."
  name: "cas.authn.cognito.client-id"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Connection timeout."
  name: "cas.authn.cognito.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  name: "cas.authn.cognito.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  name: "cas.authn.cognito.credential-secret-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  name: "cas.authn.cognito.endpoint"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Local address."
  name: "cas.authn.cognito.local-address"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  name: "cas.authn.cognito.max-connections"
  defaultValue: 10
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  name: "cas.authn.cognito.name"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.Integer"
  description: "The order of this authentication handler in the chain."
  name: "cas.authn.cognito.order"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Profile name to use."
  name: "cas.authn.cognito.profile-name"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Profile path."
  name: "cas.authn.cognito.profile-path"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  name: "cas.authn.cognito.proxy-host"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  name: "cas.authn.cognito.proxy-password"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  name: "cas.authn.cognito.proxy-username"
  defaultValue: ""
- required: true
  module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "AWS region used."
  name: "cas.authn.cognito.region"
  defaultValue: ""
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  name: "cas.authn.cognito.retry-mode"
  defaultValue: "STANDARD"
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "Socket timeout."
  name: "cas.authn.cognito.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  name: "cas.authn.cognito.use-reaper"
  defaultValue: false
- required: true
  module: "cas-server-support-aws-cognito-authentication"
  owner: "org.apereo.cas.configuration.model.support.cognito.AmazonCognitoAuthenticationProperties"
  type: "java.lang.String"
  description: "The user pool identifiers where accounts may be located."
  name: "cas.authn.cognito.user-pool-id"
  defaultValue: ""
