---
- module: "cas-server-support-rest-authentication"
  owner: "org.apereo.cas.configuration.model.support.rest.RestAuthenticationProperties"
  type: "java.lang.String"
  description: "Charset to encode the credentials sent to the REST endpoint."
  shortDescription: "Charset to encode the credentials sent to the REST endpoint."
  name: "cas.authn.rest.charset"
  defaultValue: "US-ASCII"
- module: "cas-server-support-rest-authentication"
  owner: "org.apereo.cas.configuration.model.support.rest.RestAuthenticationProperties"
  type: "java.lang.String"
  description: "Name of the authentication handler."
  shortDescription: "Name of the authentication handler."
  name: "cas.authn.rest.name"
  defaultValue: ""
- required: true
  module: "cas-server-support-rest-authentication"
  owner: "org.apereo.cas.configuration.model.support.rest.RestAuthenticationProperties"
  type: "java.lang.String"
  description: "Endpoint URI to use for verification of credentials."
  shortDescription: "Endpoint URI to use for verification of credentials."
  name: "cas.authn.rest.uri"
  defaultValue: ""
