---
- module: "cas-server-support-saml-idp-metadata-rest"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RestSamlMetadataProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ password for authentication."
  name: "cas.authn.saml-idp.metadata.rest.basic-auth-password"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-rest"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RestSamlMetadataProperties"
  type: "java.lang.String"
  description: "If REST endpoint is protected via basic authentication, specify the\
    \ username for authentication."
  name: "cas.authn.saml-idp.metadata.rest.basic-auth-username"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-rest"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RestSamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Whether identity provider metadata artifacts are expected to be found\
    \ in the database."
  name: "cas.authn.saml-idp.metadata.rest.idp-metadata-enabled"
  defaultValue: false
- module: "cas-server-support-saml-idp-metadata-rest"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RestSamlMetadataProperties"
  type: "java.lang.String"
  description: "HTTP method to use when contacting the rest endpoint. Examples include\
    \ {@code GET, POST}, etc."
  name: "cas.authn.saml-idp.metadata.rest.method"
  defaultValue: "GET"
- required: true
  module: "cas-server-support-saml-idp-metadata-rest"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.RestSamlMetadataProperties"
  type: "java.lang.String"
  description: "The endpoint URL to contact and retrieve attributes."
  name: "cas.authn.saml-idp.metadata.rest.url"
  defaultValue: ""
