---
- method: "GET"
  path: "env"
  signature: "EnvironmentEndpoint.environment(java.lang.String)"
  owner: "org.springframework.boot.actuate.env.EnvironmentEndpoint"
  returnType: "EnvironmentDescriptor"
  casEndpoint: false
  parameters:
  - required: false
    type: "String"
    selector: false
- method: "GET"
  path: "env/${toMatch}"
  signature: "EnvironmentEndpoint.environmentEntry(java.lang.String)"
  owner: "org.springframework.boot.actuate.env.EnvironmentEndpoint"
  returnType: "EnvironmentEntryDescriptor"
  casEndpoint: false
  parameters:
  - required: true
    type: "String"
    selector: true
