---
- method: "GET"
  path: "scheduledtasks"
  signature: "ScheduledTasksEndpoint.scheduledTasks()"
  owner: "org.springframework.boot.actuate.scheduling.ScheduledTasksEndpoint"
  returnType: "ScheduledTasksReport"
  casEndpoint: false
