---
- method: "GET"
  path: "scheduledtasks"
  signature: "ScheduledTasksEndpoint$ScheduledTasksReport org.springframework.boot.actuate.scheduling.ScheduledTasksEndpoint.scheduledTasks()"
  returnType: "ScheduledTasksReport"
