---
- method: "GET"
  path: "scheduledtasks"
  name: "scheduledtasks"
  endpointType: "Endpoint"
  signature: "ScheduledTasksEndpoint.scheduledTasks()"
  owner: "org.springframework.boot.actuate.scheduling.ScheduledTasksEndpoint"
  returnType: "ScheduledTasksReport"
  casEndpoint: false
