---
- method: "GET"
  path: "oauthTokens"
  signature: "OAuth20TokenManagementEndpoint.getTokens()"
  owner: "org.apereo.cas.support.oauth.web.mgmt.OAuth20TokenManagementEndpoint"
  returnType: "Collection"
  casEndpoint: true
  summary: "Get access and/or refresh tokens."
- method: "GET"
  path: "oauthTokens/${token}"
  signature: "OAuth20TokenManagementEndpoint.getToken(java.lang.String)"
  owner: "org.apereo.cas.support.oauth.web.mgmt.OAuth20TokenManagementEndpoint"
  returnType: "Ticket"
  casEndpoint: true
  summary: "Get single token by id."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "token"
- method: "DELETE"
  path: "oauthTokens/${ticketId}"
  signature: "OAuth20TokenManagementEndpoint.deleteToken(java.lang.String)"
  owner: "org.apereo.cas.support.oauth.web.mgmt.OAuth20TokenManagementEndpoint"
  casEndpoint: true
  summary: "Delete token by id."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "ticketId"
