---
- module: "cas-server-support-oauth"
  owner: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties"
  type: "org.apereo.cas.configuration.model.support.oauth.OAuthAccessTokenProperties"
  description: "Settings related to oauth access tokens."
  shortDescription: "Settings related to oauth access tokens."
  name: "cas.authn.oauth.access-token"
  defaultValue: ""
- module: "cas-server-support-oauth"
  owner: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties"
  type: "org.apereo.cas.configuration.model.support.oauth.OAuthCodeProperties"
  description: "Settings related to oauth codes."
  shortDescription: "Settings related to oauth codes."
  name: "cas.authn.oauth.code"
  defaultValue: ""
- module: "cas-server-support-oauth"
  owner: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties"
  type: "org.apereo.cas.configuration.model.support.oauth.OAuthDeviceTokenProperties"
  description: "Settings related to oauth device tokens."
  shortDescription: "Settings related to oauth device tokens."
  name: "cas.authn.oauth.device-token"
  defaultValue: ""
- module: "cas-server-support-oauth"
  owner: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties"
  type: "org.apereo.cas.configuration.model.support.oauth.OAuthDeviceUserCodeProperties"
  description: "Settings related to oauth device user codes."
  shortDescription: "Settings related to oauth device user codes."
  name: "cas.authn.oauth.device-user-code"
  defaultValue: ""
- module: "cas-server-support-oauth"
  owner: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties"
  type: "org.apereo.cas.configuration.model.support.oauth.OAuthGrantsProperties"
  description: "Settings related to oauth grants."
  shortDescription: "Settings related to oauth grants."
  name: "cas.authn.oauth.grants"
  defaultValue: ""
- module: "cas-server-support-oauth"
  owner: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties"
  type: "org.apereo.cas.configuration.model.support.oauth.OAuthRefreshTokenProperties"
  description: "Settings related to oauth refresh tokens."
  shortDescription: "Settings related to oauth refresh tokens."
  name: "cas.authn.oauth.refresh-token"
  defaultValue: ""
- module: "cas-server-support-oauth"
  owner: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties"
  type: "java.lang.Boolean"
  description: "Indicates whether profiles and other session data, collected as part\
    \ of OAuth flows and requests that are kept by the container session, should be\
    \ replicated across the cluster using CAS and its own ticket registry. Without\
    \ this option, OAuth profile data and other related pieces of information should\
    \ be manually replicated via means and libraries outside of CAS."
  shortDescription: "Indicates whether profiles and other session data, collected\
    \ as part of OAuth flows and requests that are kept by the container session,\
    \ should be replicated across the cluster using CAS and its own ticket registry."
  name: "cas.authn.oauth.replicate-sessions"
  defaultValue: false
- module: "cas-server-support-oauth"
  owner: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties"
  type: "org.apereo.cas.configuration.model.support.oauth.OAuthProperties$UserProfileViewTypes"
  description: "User profile view type determines how the final user profile should\
    \ be rendered once an access token is \"validated\".\nAvailable values are as\
    \ follows:\n<ul><li>{@code NESTED}: Return and render the user profile view in\
    \ nested mode.\nThis is the default option, most usually.</li><li>{@code FLAT}:\
    \ Return and render the user profile view in flattened mode\nwhere all attributes\
    \ are flattened down to one level only.</li></ul>"
  shortDescription: "User profile view type determines how the final user profile\
    \ should be rendered once an access token is \"validated\"."
  name: "cas.authn.oauth.user-profile-view-type"
  defaultValue: ""
