---
- method: "POST"
  path: "resume"
  signature: "ResumeEndpoint.resume()"
  owner: "org.springframework.cloud.context.restart.RestartEndpoint$ResumeEndpoint"
  returnType: "Boolean"
  casEndpoint: false
