---
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "boolean"
  description: "Whether CAS should enable its own attribute resolution machinery\n\
    after having received a response from wsfed."
  name: "cas.authn.wsfed[].attribute-resolver-enabled"
  defaultValue: true
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "Indicates how attributes should be recorded into the principal object.\n\
    Useful if you wish to additionally resolve attributes on top of what wsfed provides.\n\
    Accepted values are {@code CAS,WSFED,BOTH}."
  name: "cas.authn.wsfed[].attributes-type"
  defaultValue: "WSFED"
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "boolean"
  description: "Whether CAS should auto redirect to this wsfed instance."
  name: "cas.authn.wsfed[].auto-redirect"
  defaultValue: true
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "java.lang.String"
  description: "CAS Cookie comment, describes the cookie's usage and purpose."
  name: "cas.authn.wsfed[].cookie.comment"
  defaultValue: "CAS Cookie"
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "java.lang.String"
  description: "Cookie domain. Specifies the domain within which this cookie should\
    \ be presented.\nThe form of the domain name is specified by RFC 2965. A domain\
    \ name begins with a dot (.foo.com)\nand means that the cookie is visible to servers\
    \ in a\nspecified Domain Name System (DNS) zone (for example, www.foo.com, but\
    \ not a.b.foo.com).\nBy default, cookies are only returned to the server that\
    \ sent them."
  name: "cas.authn.wsfed[].cookie.domain"
  defaultValue: ""
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "boolean"
  description: "true if this cookie contains the HttpOnly attribute. This means that\
    \ the cookie should\nnot be accessible to scripting engines, like javascript."
  name: "cas.authn.wsfed[].cookie.http-only"
  defaultValue: true
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "int"
  description: "The maximum age of the cookie, specified in seconds. By default, -1\
    \ indicating\nthe cookie will persist until browser shutdown.\nA positive value\
    \ indicates that the cookie will expire after that many seconds have passed. Note\
    \ that the value is\nthe maximum age when the cookie will expire, not the cookie's\
    \ current age.\nA negative value means that the cookie is not stored persistently\
    \ and will be deleted when the Web browser exits.\nA zero value causes the cookie\
    \ to be deleted."
  name: "cas.authn.wsfed[].cookie.max-age"
  defaultValue: ""
- required: true
  module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "java.lang.String"
  description: "Cookie name. Constructs a cookie with a specified name and value.\n\
    The name must conform to RFC 2965. That means it can contain only ASCII alphanumeric\
    \ characters and\ncannot contain commas, semicolons, or white space or begin with\
    \ a $ character.\nThe cookie's name cannot be changed after creation.\nBy default,\
    \ cookies are created according to the RFC 2965 cookie specification."
  name: "cas.authn.wsfed[].cookie.name"
  defaultValue: ""
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "java.lang.String"
  description: "Cookie path.\nSpecifies a path for the cookie to which the client\
    \ should return the cookie.\nThe cookie is visible to all the pages in the directory\
    \ you specify, and all the pages in that directory's\nsubdirectories. A cookie's\
    \ path must include the servlet that set the cookie, for example, /catalog,\n\
    which makes the cookie visible to all directories on the server under /catalog.\n\
    Consult RFC 2965 (available on the Internet) for more information on setting path\
    \ names for cookies."
  name: "cas.authn.wsfed[].cookie.path"
  defaultValue: ""
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "boolean"
  description: "When generating cookie values, determine whether the value\nshould\
    \ be compounded and signed with the properties of\nthe current session, such as\
    \ IP address, user-agent, etc."
  name: "cas.authn.wsfed[].cookie.pin-to-session"
  defaultValue: true
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "java.lang.String"
  description: "If a cookie is only intended to be accessed in a first party context,\
    \ the\ndeveloper has the option to apply one of settings\n{@code SameSite=Lax\
    \ or SameSite=Strict or SameSite=None} to prevent external access.\n<p>\nTo safeguard\
    \ more websites and their users, the new secure-by-default model\nassumes all\
    \ cookies should be protected from external access unless otherwise\nspecified.\
    \ Developers must use a new cookie setting, {@code SameSite=None}, to designate\n\
    cookies for cross-site access. When the {@code SameSite=None} attribute is present,\
    \ an additional\n{@code Secure} attribute is used so cross-site cookies can only\
    \ be accessed over HTTPS\nconnections.\n</p>\n<p>Accepted values are: {@code Lax},\
    \ {@code Strict},  {@code None}.</p>"
  name: "cas.authn.wsfed[].cookie.same-site-policy"
  defaultValue: ""
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegatedCookieProperties"
  type: "boolean"
  description: "True if sending this cookie should be restricted to a secure protocol,\
    \ or\nfalse if the it can be sent using any protocol."
  name: "cas.authn.wsfed[].cookie.secure"
  defaultValue: true
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "The path to the public key/certificate used to handle and verify encrypted\
    \ assertions."
  name: "cas.authn.wsfed[].encryption-certificate"
  defaultValue: "classpath:certificate.crt"
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "The path to the private key used to handle and verify encrypted assertions."
  name: "cas.authn.wsfed[].encryption-private-key"
  defaultValue: "classpath:private.key"
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "The private key password."
  name: "cas.authn.wsfed[].encryption-private-key-password"
  defaultValue: "NONE"
- required: true
  module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "The attribute extracted from the assertion and used to construct the\
    \ CAS principal id."
  name: "cas.authn.wsfed[].identity-attribute"
  defaultValue: "upn"
- required: true
  module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "The entity id or the identifier of the Wsfed instance."
  name: "cas.authn.wsfed[].identity-provider-identifier"
  defaultValue: "http://adfs.example.org/adfs/services/trust"
- required: true
  module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "Wsfed identity provider url."
  name: "cas.authn.wsfed[].identity-provider-url"
  defaultValue: "https://adfs.example.org/adfs/ls/"
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "Name of the authentication handler."
  name: "cas.authn.wsfed[].name"
  defaultValue: ""
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "int"
  description: "The order of the authentication handler in the chain."
  name: "cas.authn.wsfed[].order"
  defaultValue: ""
- required: true
  module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "The identifier for CAS (RP) registered with wsfed."
  name: "cas.authn.wsfed[].relying-party-identifier"
  defaultValue: "urn:cas:localhost"
- required: true
  module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "Locations of signing certificates used to verify assertions."
  name: "cas.authn.wsfed[].signing-certificate-resources"
  defaultValue: "classpath:adfs-signing.crt"
- module: "cas-server-support-wsfederation-webflow"
  owner: "org.apereo.cas.configuration.model.support.wsfed.WsFederationDelegationProperties"
  type: "java.lang.String"
  description: "Tolerance value used to skew assertions to support clock drift."
  name: "cas.authn.wsfed[].tolerance"
  defaultValue: "PT10S"
