---
- module: "cas-server-support-consent-rest"
  owner: "org.apereo.cas.configuration.model.support.consent.RestfulConsentProperties"
  type: "java.lang.String"
  description: "REST endpoint to use to which consent decision records will be submitted."
  shortDescription: "REST endpoint to use to which consent decision records will be\
    \ submitted."
  name: "cas.consent.rest.endpoint"
  defaultValue: ""
