---
- required: true
  module: "cas-server-support-yubikey-redis"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyRedisMultifactorProperties"
  type: "java.lang.Integer"
  description: "Database index used by the connection factory."
  shortDescription: "Database index used by the connection factory."
  name: "cas.authn.mfa.yubikey.redis.database"
  defaultValue: 0
- required: true
  module: "cas-server-support-yubikey-redis"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyRedisMultifactorProperties"
  type: "java.lang.String"
  description: "Redis server host."
  shortDescription: "Redis server host."
  name: "cas.authn.mfa.yubikey.redis.host"
  defaultValue: "localhost"
- required: true
  module: "cas-server-support-yubikey-redis"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyRedisMultifactorProperties"
  type: "java.lang.String"
  description: "Login password of the redis server."
  shortDescription: "Login password of the redis server."
  name: "cas.authn.mfa.yubikey.redis.password"
  defaultValue: ""
- required: true
  module: "cas-server-support-yubikey-redis"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyRedisMultifactorProperties"
  type: "java.lang.Integer"
  description: "Redis server port."
  shortDescription: "Redis server port."
  name: "cas.authn.mfa.yubikey.redis.port"
  defaultValue: 6379
- module: "cas-server-support-yubikey-redis"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyRedisMultifactorProperties"
  type: "java.lang.String"
  description: "Setting that describes how Lettuce routes read operations to replica\
    \ nodes. Accepted mode are : <ul> <li>{@code MASTER}: Default mode. Read from\
    \ the current master node.</li> <li>{@code MASTER_PREFERRED}: Read from the master,\
    \ but if it is unavailable, read from replica nodes.</li> <li>{@code REPLICA/SLAVE}:\
    \ Read from replica nodes. The value REPLICA should be used from lettuce-core\
    \ version 5.2.</li> <li>{@code REPLICA_PREFERRED/SLAVE_PREFERRED}: Read from the\
    \ replica nodes, but if none is unavailable, read from the master. The value REPLICA_PREFERRED\
    \ should be used from lettuce-core version 5.2.</li> <li>{@code NEAREST}: Read\
    \ from any node of the cluster with the lowest latency.</li> <li>{@code ANY}:\
    \ Read from any node of the cluster.The value should be used from lettuce-core\
    \ version 5.2.</li> </ul>"
  shortDescription: "Setting that describes how Lettuce routes read operations to\
    \ replica nodes."
  name: "cas.authn.mfa.yubikey.redis.read-from"
  defaultValue: ""
- module: "cas-server-support-yubikey-redis"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyRedisMultifactorProperties"
  type: "java.lang.Integer"
  description: "Connection timeout in milliseconds."
  shortDescription: "Connection timeout in milliseconds."
  name: "cas.authn.mfa.yubikey.redis.timeout"
  defaultValue: 2000
- module: "cas-server-support-yubikey-redis"
  owner: "org.apereo.cas.configuration.model.support.mfa.yubikey.YubiKeyRedisMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Whether or not to use SSL for connection factory."
  shortDescription: "Whether or not to use SSL for connection factory."
  name: "cas.authn.mfa.yubikey.redis.use-ssl"
  defaultValue: false
