---
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.String"
  description: "Attribute name to collect from the authentication event to serve as\
    \ the cookie value."
  name: "cas.google-analytics.cookie.attribute-name"
  defaultValue: ""
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.String"
  description: "A regular expression pattern that is tested against attribute values\
    \ to only release and allow those that produce a successful match."
  name: "cas.google-analytics.cookie.attribute-value-pattern"
  defaultValue: ".+"
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.String"
  description: "CAS Cookie comment, describes the cookie's usage and purpose."
  name: "cas.google-analytics.cookie.comment"
  defaultValue: "CAS Cookie"
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.String"
  description: "Cookie domain. Specifies the domain within which this cookie should\
    \ be presented. The form of the domain name is specified by RFC 2965. A domain\
    \ name begins with a dot (.foo.com) and means that the cookie is visible to servers\
    \ in a specified Domain Name System (DNS) zone (for example, www.foo.com, but\
    \ not a.b.foo.com). By default, cookies are only returned to the server that sent\
    \ them."
  name: "cas.google-analytics.cookie.domain"
  defaultValue: ""
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.Boolean"
  description: "true if this cookie contains the HttpOnly attribute. This means that\
    \ the cookie should not be accessible to scripting engines, like javascript."
  name: "cas.google-analytics.cookie.http-only"
  defaultValue: true
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.Integer"
  description: "The maximum age of the cookie, specified in seconds. By default, -1\
    \ indicating the cookie will persist until browser shutdown. A positive value\
    \ indicates that the cookie will expire after that many seconds have passed. Note\
    \ that the value is the maximum age when the cookie will expire, not the cookie's\
    \ current age. A negative value means that the cookie is not stored persistently\
    \ and will be deleted when the Web browser exits. A zero value causes the cookie\
    \ to be deleted."
  name: "cas.google-analytics.cookie.max-age"
  defaultValue: -1
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.String"
  description: "Cookie name. Constructs a cookie with a specified name and value.\
    \ The name must conform to RFC 2965. That means it can contain only ASCII alphanumeric\
    \ characters and cannot contain commas, semicolons, or white space or begin with\
    \ a $ character. The cookie's name cannot be changed after creation. By default,\
    \ cookies are created according to the RFC 2965 cookie specification."
  name: "cas.google-analytics.cookie.name"
  defaultValue: ""
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.String"
  description: "Cookie path. Specifies a path for the cookie to which the client should\
    \ return the cookie. The cookie is visible to all the pages in the directory you\
    \ specify, and all the pages in that directory's subdirectories. A cookie's path\
    \ must include the servlet that set the cookie, for example, /catalog, which makes\
    \ the cookie visible to all directories on the server under /catalog. Consult\
    \ RFC 2965 (available on the Internet) for more information on setting path names\
    \ for cookies."
  name: "cas.google-analytics.cookie.path"
  defaultValue: ""
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.Boolean"
  description: "When generating cookie values, determine whether the value should\
    \ be compounded and signed with the properties of the current session, such as\
    \ IP address, user-agent, etc."
  name: "cas.google-analytics.cookie.pin-to-session"
  defaultValue: true
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.String"
  description: "If a cookie is only intended to be accessed in a first party context,\
    \ the developer has the option to apply one of settings {@code SameSite=Lax or\
    \ SameSite=Strict or SameSite=None} to prevent external access. <p> To safeguard\
    \ more websites and their users, the new secure-by-default model assumes all cookies\
    \ should be protected from external access unless otherwise specified. Developers\
    \ must use a new cookie setting, {@code SameSite=None}, to designate cookies for\
    \ cross-site access. When the {@code SameSite=None} attribute is present, an additional\
    \ {@code Secure} attribute is used so cross-site cookies can only be accessed\
    \ over HTTPS connections. </p> <p>Accepted values are: {@code Lax}, {@code Strict},\
    \  {@code None}.</p>"
  name: "cas.google-analytics.cookie.same-site-policy"
  defaultValue: ""
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsCookieProperties"
  type: "java.lang.Boolean"
  description: "True if sending this cookie should be restricted to a secure protocol,\
    \ or false if the it can be sent using any protocol."
  name: "cas.google-analytics.cookie.secure"
  defaultValue: true
- module: "cas-server-support-google-analytics"
  owner: "org.apereo.cas.configuration.model.support.analytics.GoogleAnalyticsProperties"
  type: "java.lang.String"
  description: "The tracking id. Configuring the tracking activated google analytics\
    \ in CAS on UI views, etc."
  name: "cas.google-analytics.google-analytics-tracking-id"
  defaultValue: ""
