---
- method: "GET"
  path: "resolveAttributes/${uid}"
  signature: "CasResolveAttributesReportEndpoint.resolvePrincipalAttributes(java.lang.String)"
  returnType: "Map"
  summary: "Resolve principal attributes for user."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "uid"
