---
- method: "GET"
  path: "u2fDevices/${username}"
  signature: "U2FRegisteredDevicesEndpoint.fetchBy(java.lang.String)"
  returnType: "Collection"
  summary: "Get all registered devices for the user."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "username"
  produces:
  - "application/json"
- method: "GET"
  path: "u2fDevices"
  signature: "U2FRegisteredDevicesEndpoint.fetchAll()"
  returnType: "Collection"
  summary: "Get all registered devices."
  produces:
  - "application/json"
- method: "DELETE"
  path: "u2fDevices/${username}/${id}"
  signature: "U2FRegisteredDevicesEndpoint.delete(java.lang.String,java.lang.Long)"
  returnType: "void"
  summary: "Delete registered device for username and device."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "username"
  - required: true
    type: "Long"
    selector: true
    name: "id"
- method: "DELETE"
  path: "u2fDevices/${username}"
  signature: "U2FRegisteredDevicesEndpoint.delete(java.lang.String)"
  returnType: "void"
  summary: "Delete all registered devices."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "username"
