---
- method: "GET"
  path: "metrics"
  signature: "MetricsEndpoint.listNames()"
  owner: "org.springframework.boot.actuate.metrics.MetricsEndpoint"
  returnType: "ListNamesResponse"
  casEndpoint: false
- method: "GET"
  path: "metrics/${requiredMetricName}"
  signature: "MetricsEndpoint.metric(java.lang.String,java.util.List<java.lang.String>)"
  owner: "org.springframework.boot.actuate.metrics.MetricsEndpoint"
  returnType: "MetricResponse"
  casEndpoint: false
  parameters:
  - required: true
    type: "String"
    selector: true
  - required: false
    type: "List"
    selector: false
