---
- required: true
  module: "cas-server-support-json-service-registry"
  owner: "org.apereo.cas.configuration.model.support.services.json.JsonServiceRegistryProperties"
  type: "org.springframework.core.io.Resource"
  description: "The location of the resource. Resources can be URLS, or files found\
    \ either on the classpath or outside somewhere in the file system."
  shortDescription: "The location of the resource."
  name: "cas.service-registry.json.location"
  defaultValue: ""
