---
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "S3 bucket that contains metadata files."
  name: "cas.authn.saml-idp.metadata.amazon-s3.bucket-name"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Client execution timeout."
  name: "cas.authn.saml-idp.metadata.amazon-s3.client-execution-timeout"
  defaultValue: "10000"
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Connection timeout."
  name: "cas.authn.saml-idp.metadata.amazon-s3.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  name: "cas.authn.saml-idp.metadata.amazon-s3.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  name: "cas.authn.saml-idp.metadata.amazon-s3.credential-secret-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  name: "cas.authn.saml-idp.metadata.amazon-s3.endpoint"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "The collection name that is responsible to hold the identity provider\
    \ metadata."
  name: "cas.authn.saml-idp.metadata.amazon-s3.idp-metadata-bucket-name"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Local address."
  name: "cas.authn.saml-idp.metadata.amazon-s3.local-address"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  name: "cas.authn.saml-idp.metadata.amazon-s3.max-connections"
  defaultValue: 10
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Profile name to use."
  name: "cas.authn.saml-idp.metadata.amazon-s3.profile-name"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Profile path."
  name: "cas.authn.saml-idp.metadata.amazon-s3.profile-path"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  name: "cas.authn.saml-idp.metadata.amazon-s3.proxy-host"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  name: "cas.authn.saml-idp.metadata.amazon-s3.proxy-password"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  name: "cas.authn.saml-idp.metadata.amazon-s3.proxy-username"
  defaultValue: ""
- required: true
  module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "AWS region used."
  name: "cas.authn.saml-idp.metadata.amazon-s3.region"
  defaultValue: ""
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  name: "cas.authn.saml-idp.metadata.amazon-s3.retry-mode"
  defaultValue: "STANDARD"
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.String"
  description: "Socket timeout."
  name: "cas.authn.saml-idp.metadata.amazon-s3.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-saml-idp-metadata-aws-s3"
  owner: "org.apereo.cas.configuration.model.support.saml.idp.metadata.AmazonS3SamlMetadataProperties"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  name: "cas.authn.saml-idp.metadata.amazon-s3.use-reaper"
  defaultValue: false
