---
- module: "cas-server-support-aup-ldap"
  owner: "org.apereo.cas.configuration.model.support.aup.ListableLdapAcceptableUsagePolicyProperties"
  type: "java.lang.Object[]"
  name: "cas.acceptable-usage-policy.ldap.element-data"
  defaultValue: ""
- module: "cas-server-support-aup-ldap"
  owner: "org.apereo.cas.configuration.model.support.aup.ListableLdapAcceptableUsagePolicyProperties"
  type: "java.lang.Integer"
  name: "cas.acceptable-usage-policy.ldap.mod-count"
  defaultValue: ""
- module: "cas-server-support-aup-ldap"
  owner: "org.apereo.cas.configuration.model.support.aup.ListableLdapAcceptableUsagePolicyProperties"
  type: "java.lang.Integer"
  name: "cas.acceptable-usage-policy.ldap.size"
  defaultValue: ""
