---
- method: "GET"
  path: "duoAccountStatus/${username}"
  signature: "DuoSecurityUserAccountStatusEndpoint.fetchAccountStatus(java.lang.String,java.lang.String)"
  returnType: "Map"
  summary: "Fetch Duo Security user account status."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "username"
  - required: false
    type: "String"
    selector: false
    name: "providerId"
  produces:
  - "application/json"
