---
- method: "GET"
  path: "ticketExpirationPolicies"
  signature: "TicketExpirationPoliciesEndpoint.handle(java.lang.String) throws java.lang.Exception"
  returnType: "Map"
  summary: "Produce expiration policies given an optional service id."
  parameters:
  - required: false
    type: "String"
    selector: false
    name: "serviceId"
