---
- name: "wsfed.relyingPartyIdentifier"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_WSFED"
- name: "jwtAsServiceTicket"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "JWT_SERVICE_TICKETS"
- name: "jwtAsServiceTicketCipherStrategyType"
  defaultValue: "ENCRYPT_AND_SIGN"
  type: "STRING"
  group: "JWT_SERVICE_TICKETS"
- name: "jwtAsServiceTicketSigningKey"
  defaultValue: ""
  type: "STRING"
  group: "JWT_SERVICE_TICKETS"
- name: "jwtAsServiceTicketEncryptionKey"
  defaultValue: ""
  type: "STRING"
  group: "JWT_SERVICE_TICKETS"
- name: "accessTokenAsJwtSigningKey"
  defaultValue: ""
  type: "STRING"
  group: "JWT_ACCESS_TOKENS"
- name: "accessTokenAsJwtCipherStrategyType"
  defaultValue: "ENCRYPT_AND_SIGN"
  type: "STRING"
  group: "JWT_ACCESS_TOKENS"
- name: "accessTokenAsJwtSigningEnabled"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "JWT_ACCESS_TOKENS"
- name: "accessTokenAsJwtEncryptionEnabled"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "JWT_ACCESS_TOKENS"
- name: "accessTokenAsJwtEncryptionKey"
  defaultValue: ""
  type: "STRING"
  group: "JWT_ACCESS_TOKENS"
- name: "jwtSigningSecret"
  defaultValue: ""
  type: "STRING"
  group: "JWT_AUTHENTICATION"
- name: "jwtSigningSecretAlg"
  defaultValue: "HS256"
  type: "STRING"
  group: "JWT_AUTHENTICATION"
- name: "jwtEncryptionSecret"
  defaultValue: ""
  type: "STRING"
  group: "JWT_AUTHENTICATION"
- name: "jwtEncryptionSecretAlg"
  defaultValue: ""
  type: "STRING"
  group: "JWT_AUTHENTICATION"
- name: "jwtEncryptionSecretMethod"
  defaultValue: "A192CBC-HS384"
  type: "STRING"
  group: "JWT_AUTHENTICATION"
- name: "jwtSecretsAreBase64Encoded"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "JWT_AUTHENTICATION"
- name: "skipInterrupt"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "INTERRUPTS"
- name: "skipRequiredServiceCheck"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "REGISTERED_SERVICES"
- name: "httpHeaderEnableCacheControl"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
- name: "httpHeaderEnableXContentOptions"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
- name: "httpHeaderEnableStrictTransportSecurity"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
- name: "httpHeaderEnableXFrameOptions"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
- name: "httpHeaderXFrameOptions"
  defaultValue: "DENY"
  type: "STRING"
  group: "HTTP_HEADERS"
- name: "httpHeaderEnableContentSecurityPolicy"
  defaultValue: "true"
  type: "STRING"
  group: "HTTP_HEADERS"
- name: "httpHeaderEnableXSSProtection"
  defaultValue: "true"
  type: "BOOLEAN"
  group: "HTTP_HEADERS"
- name: "corsAllowCredentials"
  defaultValue: "false"
  type: "BOOLEAN"
  group: "CORS"
- name: "corsMaxAge"
  defaultValue: ""
  type: "INTEGER"
  group: "CORS"
- name: "corsAllowedOrigins"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
- name: "corsAllowedOriginPatterns"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
- name: "corsAllowedMethods"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
- name: "corsAllowedHeaders"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
- name: "corsExposedHeaders"
  defaultValue: ""
  type: "STRING"
  group: "CORS"
- name: "AuthnRequestBindingType"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
- name: "AssertionConsumerServiceIndex"
  defaultValue: ""
  type: "LONG"
  group: "DELEGATED_AUTHN_SAML2"
- name: "AttributeConsumingServiceIndex"
  defaultValue: ""
  type: "LONG"
  group: "DELEGATED_AUTHN_SAML2"
- name: "ComparisonType"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
- name: "NameIdPolicyFormat"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
- name: "NameIdPolicyAllowCreate"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN_SAML2"
- name: "ProviderName"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
- name: "IssuerFormat"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
- name: "UseNameQualifier"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN_SAML2"
- name: "AuthnContextClassRefs"
  defaultValue: ""
  type: "SET"
  group: "DELEGATED_AUTHN_SAML2"
- name: "NameIdAttribute"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_SAML2"
- name: "WantsAssertionsSigned"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN_SAML2"
- name: "WantsResponsesSigned"
  defaultValue: ""
  type: "BOOLEAN"
  group: "DELEGATED_AUTHN_SAML2"
- name: "MaximumAuthenticationLifetime"
  defaultValue: ""
  type: "LONG"
  group: "DELEGATED_AUTHN_SAML2"
- name: "max_age"
  defaultValue: ""
  type: "INTEGER"
  group: "DELEGATED_AUTHN_OIDC"
- name: "scope"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_OIDC"
- name: "response_type"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_OIDC"
- name: "response_mode"
  defaultValue: ""
  type: "STRING"
  group: "DELEGATED_AUTHN_OIDC"
- name: "scimOAuthToken"
  defaultValue: ""
  type: "STRING"
  group: "SCIM"
- name: "scimUsername"
  defaultValue: ""
  type: "STRING"
  group: "SCIM"
- name: "scimPassword"
  defaultValue: ""
  type: "STRING"
  group: "SCIM"
- name: "scimTarget"
  defaultValue: ""
  type: "STRING"
  group: "SCIM"
