---
- module: "cas-server-support-throttle"
  owner: "org.apereo.cas.configuration.model.support.throttle.ThrottleProperties"
  type: "java.lang.String"
  description: "Application code used to identify this application in the audit logs."
  name: "cas.authn.throttle.app-code"
  defaultValue: "CAS"
- module: "cas-server-support-throttle"
  owner: "org.apereo.cas.configuration.model.support.throttle.ThrottleProperties.Failure"
  type: "java.lang.String"
  description: "Failure code to record in the audit log. Generally this indicates\
    \ an authentication failure event."
  name: "cas.authn.throttle.failure.code"
  defaultValue: ""
- module: "cas-server-support-throttle"
  owner: "org.apereo.cas.configuration.model.support.throttle.ThrottleProperties.Failure"
  type: "java.lang.Integer"
  description: "Period of time in seconds during which the threshold applies."
  name: "cas.authn.throttle.failure.range-seconds"
  defaultValue: -1
- module: "cas-server-support-throttle"
  owner: "org.apereo.cas.configuration.model.support.throttle.ThrottleProperties.Failure"
  type: "java.lang.Integer"
  description: "Number of failed login attempts permitted in the above period. All\
    \ login throttling components that ship with CAS limit successive failed login\
    \ attempts that exceed a threshold rate in failures per second."
  name: "cas.authn.throttle.failure.threshold"
  defaultValue: -1
- module: "cas-server-support-throttle"
  owner: "org.apereo.cas.configuration.model.support.throttle.ThrottleProperties"
  type: "java.lang.String"
  description: "Username parameter to use in order to extract the username from the\
    \ request."
  name: "cas.authn.throttle.username-parameter"
  defaultValue: ""
