---
- method: "GET"
  path: "multifactorTrustedDevices"
  signature: "MultifactorAuthenticationTrustReportEndpoint.devices()"
  returnType: "Set"
  summary: "Get collection of trusted devices."
- method: "GET"
  path: "multifactorTrustedDevices/${username}"
  signature: "MultifactorAuthenticationTrustReportEndpoint.devicesForUser(java.lang.String)"
  returnType: "Set"
  summary: "Get collection of trusted devices for the user."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "username"
- method: "DELETE"
  path: "multifactorTrustedDevices/${key}"
  signature: "MultifactorAuthenticationTrustReportEndpoint.revoke(java.lang.String)"
  returnType: "Integer"
  summary: "Remove trusted device using its key."
  parameters:
  - required: true
    type: "String"
    selector: true
    name: "key"
