---
- method: "GET"
  path: "sso"
  signature: "SingleSignOnSessionStatusEndpoint.ssoStatus(javax.servlet.http.HttpServletRequest)"
  owner: "org.apereo.cas.web.report.SingleSignOnSessionStatusEndpoint"
  returnType: "ResponseEntity"
  casEndpoint: true
  summary: "Get current status of single sign-on."
  parameters:
  - required: true
    type: "HttpServletRequest"
    selector: false
  produces:
  - "application/json"
