---
- method: "GET"
  path: "sessions/${sessionId}"
  signature: "SessionsEndpoint$SessionDescriptor org.springframework.boot.actuate.session.SessionsEndpoint.getSession(java.lang.String)"
  returnType: "SessionDescriptor"
  parameters:
  - required: true
    type: "String"
    selector: true
- method: "GET"
  path: "sessions"
  signature: "SessionsEndpoint$SessionsReport org.springframework.boot.actuate.session.SessionsEndpoint.sessionsForUsername(java.lang.String)"
  returnType: "SessionsReport"
  parameters:
  - required: true
    type: "String"
    selector: false
- method: "DELETE"
  path: "sessions/${sessionId}"
  signature: "SessionsEndpoint.deleteSession(java.lang.String)"
  returnType: "void"
  parameters:
  - required: true
    type: "String"
    selector: true
