---
- module: "cas-server-core-services"
  owner: "org.apereo.cas.configuration.model.core.services.ServiceRegistryProperties"
  type: "java.lang.String"
  description: "Services cache duration specifies the fixed duration for an entry\
    \ to be automatically removed from the cache after its creation or update."
  shortDescription: "Services cache duration specifies the fixed duration for an entry\
    \ to be automatically removed from the cache after its creation or update."
  name: "cas.service-registry.cache"
  defaultValue: "PT5M"
- module: "cas-server-core-services"
  owner: "org.apereo.cas.configuration.model.core.services.ServiceRegistryProperties"
  type: "java.lang.Integer"
  description: "Services cache capacity sets the minimum total size for the internal\
    \ data structures."
  shortDescription: "Services cache capacity sets the minimum total size for the internal\
    \ data structures."
  name: "cas.service-registry.cache-capacity"
  defaultValue: 1000
- module: "cas-server-core-services"
  owner: "org.apereo.cas.configuration.model.core.services.ServiceRegistryProperties"
  type: "java.lang.Long"
  description: "Services cache size specifies the maximum number of entries the cache\
    \ may contain."
  shortDescription: "Services cache size specifies the maximum number of entries the\
    \ cache may contain."
  name: "cas.service-registry.cache-size"
  defaultValue: 1000
- module: "cas-server-core-services"
  owner: "org.apereo.cas.configuration.model.core.services.ServiceRegistryProperties"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to initialise active service registry\
    \ implementation with a default set of service definition included with CAS in\
    \ JSON format."
  shortDescription: "Flag that indicates whether to initialise active service registry\
    \ implementation with a default set of service definition included with CAS in\
    \ JSON format."
  name: "cas.service-registry.init-from-json"
  defaultValue: false
- module: "cas-server-core-services"
  owner: "org.apereo.cas.configuration.model.core.services.ServiceRegistryProperties"
  type: "org.apereo.cas.configuration.model.core.services.ServiceRegistryProperties$ServiceManagementTypes"
  description: "Determine how services are internally managed, queried, cached and\
    \ reloaded by CAS. Accepted values are the following: <ul> <li>DEFAULT: Keep all\
    \ services inside a concurrent map.</li> <li>DOMAIN: Group registered services\
    \ by their domain having been explicitly defined.</li> </ul>\nAvailable values\
    \ are as follows:\n<ul><li>{@code DOMAIN}: Group service definitions by their\
    \ domain.</li><li>{@code DEFAULT}: Default option to keep definitions in a map\
    \ as they arrive.</li></ul>"
  shortDescription: "Determine how services are internally managed, queried, cached\
    \ and reloaded by CAS."
  name: "cas.service-registry.management-type"
  defaultValue: ""
- module: "cas-server-core-services"
  owner: "org.apereo.cas.configuration.model.core.services.ServiceRegistryProperties"
  type: "java.lang.Boolean"
  description: "Flag indicating whether a background watcher thread is enabled for\
    \ the purposes of live reloading of service registry data changes from persistent\
    \ data store."
  shortDescription: "Flag indicating whether a background watcher thread is enabled\
    \ for the purposes of live reloading of service registry data changes from persistent\
    \ data store."
  name: "cas.service-registry.watcher-enabled"
  defaultValue: true
