---
- module: "cas-server-core-configuration"
  owner: "org.apereo.cas.configuration.model.core.config.standalone.StandaloneConfigurationProperties"
  type: "java.io.File"
  description: "Describes a directory path where CAS configuration may be found."
  shortDescription: "Describes a directory path where CAS configuration may be found."
  name: "cas.standalone.configuration-directory"
  defaultValue: ""
- module: "cas-server-core-configuration"
  owner: "org.apereo.cas.configuration.model.core.config.standalone.StandaloneConfigurationProperties"
  type: "java.io.File"
  description: "Describes a file path where that contains the CAS properties in a\
    \ single file."
  shortDescription: "Describes a file path where that contains the CAS properties\
    \ in a single file."
  name: "cas.standalone.configuration-file"
  defaultValue: ""
- module: "cas-server-core-configuration"
  owner: "org.apereo.cas.configuration.model.core.config.standalone.StandaloneConfigurationSecurityProperties"
  type: "java.lang.String"
  description: "Algorithm to use when deciphering settings."
  shortDescription: "Algorithm to use when deciphering settings."
  name: "cas.standalone.configuration-security.alg"
  defaultValue: ""
- module: "cas-server-core-configuration"
  owner: "org.apereo.cas.configuration.model.core.config.standalone.StandaloneConfigurationSecurityProperties"
  type: "java.lang.Long"
  description: "Total number of iterations to use when deciphering settings."
  shortDescription: "Total number of iterations to use when deciphering settings."
  name: "cas.standalone.configuration-security.iteration"
  defaultValue: 0
- module: "cas-server-core-configuration"
  owner: "org.apereo.cas.configuration.model.core.config.standalone.StandaloneConfigurationSecurityProperties"
  type: "java.lang.String"
  description: "Security provider to use when deciphering settings."
  shortDescription: "Security provider to use when deciphering settings."
  name: "cas.standalone.configuration-security.provider"
  defaultValue: ""
- module: "cas-server-core-configuration"
  owner: "org.apereo.cas.configuration.model.core.config.standalone.StandaloneConfigurationSecurityProperties"
  type: "java.lang.String"
  description: "Secret key/password to use when deciphering settings."
  shortDescription: "Secret key/password to use when deciphering settings."
  name: "cas.standalone.configuration-security.psw"
  defaultValue: ""
