---
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Client execution timeout."
  shortDescription: "Client execution timeout."
  name: "cas.spring.cloud.aws.dynamo-db.client-execution-timeout"
  defaultValue: "10000"
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Connection timeout."
  shortDescription: "Connection timeout."
  name: "cas.spring.cloud.aws.dynamo-db.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  shortDescription: "Use access-key provided by AWS to authenticate."
  name: "cas.spring.cloud.aws.dynamo-db.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  shortDescription: "Use secret key provided by AWS to authenticate."
  name: "cas.spring.cloud.aws.dynamo-db.credential-secret-key"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to drop tables on start up."
  shortDescription: "Flag that indicates whether to drop tables on start up."
  name: "cas.spring.cloud.aws.dynamo-db.drop-tables-on-startup"
  defaultValue: false
- required: true
  module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  shortDescription: "AWS custom endpoint."
  name: "cas.spring.cloud.aws.dynamo-db.endpoint"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Local address."
  shortDescription: "Local address."
  name: "cas.spring.cloud.aws.dynamo-db.local-address"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Boolean"
  description: "Indicates that the database instance is local to the deployment that\
    \ does not require or use any credentials or other configuration other than host\
    \ and region. This is mostly used during development and testing."
  shortDescription: "Indicates that the database instance is local to the deployment\
    \ that does not require or use any credentials or other configuration other than\
    \ host and region."
  name: "cas.spring.cloud.aws.dynamo-db.local-instance"
  defaultValue: false
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  shortDescription: "Maximum connections setting."
  name: "cas.spring.cloud.aws.dynamo-db.max-connections"
  defaultValue: 10
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to prevent CAS from creating tables."
  shortDescription: "Flag that indicates whether to prevent CAS from creating tables."
  name: "cas.spring.cloud.aws.dynamo-db.prevent-table-creation-on-startup"
  defaultValue: false
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Profile name to use."
  shortDescription: "Profile name to use."
  name: "cas.spring.cloud.aws.dynamo-db.profile-name"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Profile path."
  shortDescription: "Profile path."
  name: "cas.spring.cloud.aws.dynamo-db.profile-path"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  shortDescription: "Optionally specifies the proxy host to connect through."
  name: "cas.spring.cloud.aws.dynamo-db.proxy-host"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  shortDescription: "Optionally specifies the proxy password to connect through."
  name: "cas.spring.cloud.aws.dynamo-db.proxy-password"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  shortDescription: "Optionally specifies the proxy username to connect through."
  name: "cas.spring.cloud.aws.dynamo-db.proxy-username"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Long"
  description: "Read capacity."
  shortDescription: "Read capacity."
  name: "cas.spring.cloud.aws.dynamo-db.read-capacity"
  defaultValue: 10
- required: true
  module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "AWS region used."
  shortDescription: "AWS region used."
  name: "cas.spring.cloud.aws.dynamo-db.region"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  shortDescription: "Outline the requested retry mode."
  name: "cas.spring.cloud.aws.dynamo-db.retry-mode"
  defaultValue: "STANDARD"
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Socket timeout."
  shortDescription: "Socket timeout."
  name: "cas.spring.cloud.aws.dynamo-db.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Integer"
  description: "Time offset."
  shortDescription: "Time offset."
  name: "cas.spring.cloud.aws.dynamo-db.time-offset"
  defaultValue: 0
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  shortDescription: "Flag that indicates whether to use reaper."
  name: "cas.spring.cloud.aws.dynamo-db.use-reaper"
  defaultValue: false
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Long"
  description: "Write capacity."
  shortDescription: "Write capacity."
  name: "cas.spring.cloud.aws.dynamo-db.write-capacity"
  defaultValue: 10
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Client execution timeout."
  shortDescription: "Client execution timeout."
  name: "cas.spring.cloud.dynamo-db.client-execution-timeout"
  defaultValue: "10000"
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Connection timeout."
  shortDescription: "Connection timeout."
  name: "cas.spring.cloud.dynamo-db.connection-timeout"
  defaultValue: "5000"
- required: true
  module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Use access-key provided by AWS to authenticate."
  shortDescription: "Use access-key provided by AWS to authenticate."
  name: "cas.spring.cloud.dynamo-db.credential-access-key"
  defaultValue: ""
- required: true
  module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Use secret key provided by AWS to authenticate."
  shortDescription: "Use secret key provided by AWS to authenticate."
  name: "cas.spring.cloud.dynamo-db.credential-secret-key"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to drop tables on start up."
  shortDescription: "Flag that indicates whether to drop tables on start up."
  name: "cas.spring.cloud.dynamo-db.drop-tables-on-startup"
  defaultValue: false
- required: true
  module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "AWS custom endpoint."
  shortDescription: "AWS custom endpoint."
  name: "cas.spring.cloud.dynamo-db.endpoint"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Local address."
  shortDescription: "Local address."
  name: "cas.spring.cloud.dynamo-db.local-address"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Boolean"
  description: "Indicates that the database instance is local to the deployment that\
    \ does not require or use any credentials or other configuration other than host\
    \ and region. This is mostly used during development and testing."
  shortDescription: "Indicates that the database instance is local to the deployment\
    \ that does not require or use any credentials or other configuration other than\
    \ host and region."
  name: "cas.spring.cloud.dynamo-db.local-instance"
  defaultValue: false
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Integer"
  description: "Maximum connections setting."
  shortDescription: "Maximum connections setting."
  name: "cas.spring.cloud.dynamo-db.max-connections"
  defaultValue: 10
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to prevent CAS from creating tables."
  shortDescription: "Flag that indicates whether to prevent CAS from creating tables."
  name: "cas.spring.cloud.dynamo-db.prevent-table-creation-on-startup"
  defaultValue: false
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Profile name to use."
  shortDescription: "Profile name to use."
  name: "cas.spring.cloud.dynamo-db.profile-name"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Profile path."
  shortDescription: "Profile path."
  name: "cas.spring.cloud.dynamo-db.profile-path"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Optionally specifies the proxy host to connect through."
  shortDescription: "Optionally specifies the proxy host to connect through."
  name: "cas.spring.cloud.dynamo-db.proxy-host"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Optionally specifies the proxy password to connect through."
  shortDescription: "Optionally specifies the proxy password to connect through."
  name: "cas.spring.cloud.dynamo-db.proxy-password"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Optionally specifies the proxy username to connect through."
  shortDescription: "Optionally specifies the proxy username to connect through."
  name: "cas.spring.cloud.dynamo-db.proxy-username"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Long"
  description: "Read capacity."
  shortDescription: "Read capacity."
  name: "cas.spring.cloud.dynamo-db.read-capacity"
  defaultValue: 10
- required: true
  module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "AWS region used."
  shortDescription: "AWS region used."
  name: "cas.spring.cloud.dynamo-db.region"
  defaultValue: ""
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Outline the requested retry mode. Accepted values are {@code STANDARD,\
    \ LEGACY}."
  shortDescription: "Outline the requested retry mode."
  name: "cas.spring.cloud.dynamo-db.retry-mode"
  defaultValue: "STANDARD"
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.String"
  description: "Socket timeout."
  shortDescription: "Socket timeout."
  name: "cas.spring.cloud.dynamo-db.socket-timeout"
  defaultValue: "5000"
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Integer"
  description: "Time offset."
  shortDescription: "Time offset."
  name: "cas.spring.cloud.dynamo-db.time-offset"
  defaultValue: 0
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Boolean"
  description: "Flag that indicates whether to use reaper."
  shortDescription: "Flag that indicates whether to use reaper."
  name: "cas.spring.cloud.dynamo-db.use-reaper"
  defaultValue: false
- module: "cas-server-support-configuration-cloud-dynamodb"
  owner: "org.apereo.cas.configuration.model.core.config.cloud.SpringCloudConfigurationProperties.AmazonDynamoDb"
  type: "java.lang.Long"
  description: "Write capacity."
  shortDescription: "Write capacity."
  name: "cas.spring.cloud.dynamo-db.write-capacity"
  defaultValue: 10
