---
- required: true
  module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "The branch to checkout and activate."
  name: "cas.service-registry.git.active-branch"
  defaultValue: "master"
- required: true
  module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "If the repository is to be cloned, this will allow the list of branches\
    \ to be fetched separated by commas."
  name: "cas.service-registry.git.branches-to-clone"
  defaultValue: "master"
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.Boolean"
  description: "When establishing an ssh session, determine if default identities\
    \ loaded on the machine should be excluded/removed and identity should only be\
    \ limitd to those loaded from given keys."
  name: "cas.service-registry.git.clear-existing-identities"
  defaultValue: false
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.Boolean"
  description: "Determine whether service definitions in the git repository should\
    \ be located/stored in groups and separate folder structures based on the service\
    \ type. @see #getRootDirectory()"
  name: "cas.service-registry.git.group-by-type"
  defaultValue: true
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "Password used to access or push to the repository."
  name: "cas.service-registry.git.password"
  defaultValue: ""
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "Password for the SSH private key."
  name: "cas.service-registry.git.private-key-passphrase"
  defaultValue: ""
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.Boolean"
  description: "Decide whether changes should be pushed back into the remote repository."
  name: "cas.service-registry.git.push-changes"
  defaultValue: false
- required: true
  module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "The address of the git repository. Could be a URL or a file-system\
    \ path."
  name: "cas.service-registry.git.repository-url"
  defaultValue: ""
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "Root directory in the git repository structure to track service definition\
    \ files. This might be most useful if the git repository is tasked with other\
    \ types of files and configurations and allowing a separate root directory for\
    \ service definitions provide a clean separation between services files and everything\
    \ else. This setting may work in concert with {@link #isGroupByType()}. If left\
    \ blank, the root folder of the git repository itself is used as the root directory\
    \ for service definitions."
  name: "cas.service-registry.git.root-directory"
  defaultValue: ""
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.Boolean"
  description: "Whether or not commits should be signed."
  name: "cas.service-registry.git.sign-commits"
  defaultValue: false
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "As with using SSH with public keys, an SSH session with {@code ssh://user@example.com/repo.git}\
    \ must be specified to use password-secured SSH connections."
  name: "cas.service-registry.git.ssh-session-password"
  defaultValue: ""
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.Boolean"
  description: "Whether on not to turn on strict host key checking. true will be \"\
    yes\", false will be \"no\", \"ask\" not supported."
  name: "cas.service-registry.git.strict-host-key-checking"
  defaultValue: true
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "Timeout for git operations such as push and pull in seconds."
  name: "cas.service-registry.git.timeout"
  defaultValue: "PT10S"
- module: "cas-server-support-git-service-registry"
  owner: "org.apereo.cas.configuration.model.support.git.services.GitServiceRegistryProperties"
  type: "java.lang.String"
  description: "Username used to access or push to the repository."
  name: "cas.service-registry.git.username"
  defaultValue: ""
