---
- method: "POST"
  path: "busenv/${destinations}"
  name: "busenv"
  endpointType: "Endpoint"
  signature: "EnvironmentBusEndpoint.busEnvWithDestination(java.lang.String,java.lang.String,java.lang.String[])"
  owner: "org.springframework.cloud.bus.endpoint.EnvironmentBusEndpoint"
  casEndpoint: false
  parameters:
  - required: true
    type: "String"
    selector: false
  - required: true
    type: "String"
    selector: false
  - required: true
    type: "String[]"
    selector: true
- method: "POST"
  path: "busenv"
  name: "busenv"
  endpointType: "Endpoint"
  signature: "EnvironmentBusEndpoint.busEnv(java.lang.String,java.lang.String)"
  owner: "org.springframework.cloud.bus.endpoint.EnvironmentBusEndpoint"
  casEndpoint: false
  parameters:
  - required: true
    type: "String"
    selector: false
  - required: true
    type: "String"
    selector: false
