---
- module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Connection timeout in milliseconds."
  shortDescription: "Connection timeout in milliseconds."
  name: "cas.authn.okta.connection-timeout"
  defaultValue: 5000
- module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.String"
  description: "A number of authentication handlers are allowed to determine whether\
    \ they can operate on the provided credential and as such lend themselves to be\
    \ tried and tested during the authentication handler selection phase. The credential\
    \ criteria may be one of the following options:<ul> <li>1) A regular expression\
    \ pattern that is tested against the credential identifier.</li> <li>2) A fully\
    \ qualified class name of your own design that implements {@code Predicate}.</li>\
    \ <li>3) Path to an external Groovy script that implements the same interface.</li>\
    \ </ul>"
  shortDescription: "A number of authentication handlers are allowed to determine\
    \ whether they can operate on the provided credential and as such lend themselves\
    \ to be tried and tested during the authentication handler selection phase."
  name: "cas.authn.okta.credential-criteria"
  defaultValue: ""
- module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler."
  shortDescription: "The name of the authentication handler."
  name: "cas.authn.okta.name"
  defaultValue: ""
- module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.Integer"
  description: "The order of this authentication handler in the chain."
  shortDescription: "The order of this authentication handler in the chain."
  name: "cas.authn.okta.order"
  defaultValue: ""
- required: true
  module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.String"
  description: "Okta domain."
  shortDescription: "Okta domain."
  name: "cas.authn.okta.organization-url"
  defaultValue: ""
- module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.String"
  description: "Send requests via a proxy; define the hostname."
  shortDescription: "Send requests via a proxy; define the hostname."
  name: "cas.authn.okta.proxy-host"
  defaultValue: ""
- module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.String"
  description: "Send requests via a proxy; define the proxy password."
  shortDescription: "Send requests via a proxy; define the proxy password."
  name: "cas.authn.okta.proxy-password"
  defaultValue: ""
- module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.Integer"
  description: "Send requests via a proxy; define the proxy port. Negative/zero values\
    \ should deactivate the proxy configuration for the http client."
  shortDescription: "Send requests via a proxy; define the proxy port."
  name: "cas.authn.okta.proxy-port"
  defaultValue: 0
- module: "cas-server-support-okta-authentication"
  owner: "org.apereo.cas.configuration.model.support.okta.OktaAuthenticationProperties"
  type: "java.lang.String"
  description: "Send requests via a proxy; define the proxy username."
  shortDescription: "Send requests via a proxy; define the proxy username."
  name: "cas.authn.okta.proxy-username"
  defaultValue: ""
