---
- method: "GET"
  path: "conditions"
  signature: "ConditionsReportEndpoint.applicationConditionEvaluation()"
  owner: "org.springframework.boot.actuate.autoconfigure.condition.ConditionsReportEndpoint"
  returnType: "ApplicationConditionEvaluation"
  casEndpoint: false
