---
- module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.String"
  description: "The failure mode policy for this MFA provider. The following failure\
    \ modes are supported: <ul>     <li>{@code CLOSED}: Authentication is blocked\
    \ if the provider cannot be reached.</li>     <li>{@code OPEN}: Authentication\
    \ proceeds yet requested MFA is NOT     communicated to the client if provider\
    \ is unavailable.</li>     <li>{@code PHANTOM}: Authentication proceeds and requested\
    \ MFA is     communicated to the client if provider is unavailable.</li>     <li>{@code\
    \ NONE}: Do not contact the provider at all to check for availability. Assume\
    \ the provider is available.</li> </ul>"
  shortDescription: "The failure mode policy for this MFA provider."
  name: "cas.authn.mfa.swivel.failure-mode"
  defaultValue: "UNDEFINED"
- module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.String"
  description: "The identifier for the multifactor provider. In most cases, this need\
    \ not be configured explicitly, unless multiple instances of the same provider\
    \ type are configured in CAS."
  shortDescription: "The identifier for the multifactor provider."
  name: "cas.authn.mfa.swivel.id"
  defaultValue: ""
- module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Control whether SSL errors should be ignored by the swivel server."
  shortDescription: "Control whether SSL errors should be ignored by the swivel server."
  name: "cas.authn.mfa.swivel.ignore-ssl-errors"
  defaultValue: false
- module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.String"
  description: "The name of the authentication handler used to verify credentials\
    \ in MFA."
  shortDescription: "The name of the authentication handler used to verify credentials\
    \ in MFA."
  name: "cas.authn.mfa.swivel.name"
  defaultValue: ""
- module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.Integer"
  description: "The order of the authentication handler in the chain."
  shortDescription: "The order of the authentication handler in the chain."
  name: "cas.authn.mfa.swivel.order"
  defaultValue: ""
- module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.Integer"
  description: "At times, CAS needs to determine the correct provider when step-up\
    \ authentication is required. Consider for a moment that CAS already has established\
    \ an SSO session with/without a provider and has reached a level of authentication.\
    \ Another incoming request attempts to exercise that SSO session with a different\
    \ and often competing authentication requirement that may differ from the authentication\
    \ level CAS has already established. Concretely, examples may be: <ul> <li>CAS\
    \ has achieved an SSO session, but a separate request now requires step-up authentication\
    \ with DuoSecurity.</li> <li>CAS has achieved an SSO session with an authentication\
    \ level satisfied by DuoSecurity, but a separate request now requires step-up\
    \ authentication with YubiKey. </li> </ul> In certain scenarios, CAS will attempt\
    \ to rank authentication levels and compare them with each other. If CAS already\
    \ has achieved a level that is higher than what the incoming request requires,\
    \ no step-up authentication will be performed. If the opposite is true, CAS will\
    \ route the authentication flow to the required authentication level and upon\
    \ success, will adjust the SSO session with the new higher authentication level\
    \ now satisfied. Ranking of authentication methods is done per provider via specific\
    \ properties for each. Note that the higher the rank value is, the higher on the\
    \ security scale it remains. A provider that ranks higher with a larger weight\
    \ value trumps and override others with a lower value."
  shortDescription: "At times, CAS needs to determine the correct provider when step-up\
    \ authentication is required."
  name: "cas.authn.mfa.swivel.rank"
  defaultValue: 0
- required: true
  module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.String"
  description: "Shared secret to authenticate against the swivel server."
  shortDescription: "Shared secret to authenticate against the swivel server."
  name: "cas.authn.mfa.swivel.shared-secret"
  defaultValue: ""
- required: true
  module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.String"
  description: "URL endpoint response to generate a turing image."
  shortDescription: "URL endpoint response to generate a turing image."
  name: "cas.authn.mfa.swivel.swivel-turing-image-url"
  defaultValue: ""
- required: true
  module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.String"
  description: "Swivel endpoint url for verification of credentials."
  shortDescription: "Swivel endpoint url for verification of credentials."
  name: "cas.authn.mfa.swivel.swivel-url"
  defaultValue: ""
- module: "cas-server-support-swivel"
  owner: "org.apereo.cas.configuration.model.support.mfa.SwivelMultifactorProperties"
  type: "java.lang.Boolean"
  description: "Indicates whether this provider should support trusted devices."
  shortDescription: "Indicates whether this provider should support trusted devices."
  name: "cas.authn.mfa.swivel.trusted-device-enabled"
  defaultValue: false
