---
- method: "GET"
  path: "mappings"
  signature: "MappingsEndpoint$ApplicationMappings org.springframework.boot.actuate.web.mappings.MappingsEndpoint.mappings()"
  returnType: "ApplicationMappings"
