---
- method: "POST"
  path: "busrefresh"
  name: "busrefresh"
  endpointType: "Endpoint"
  signature: "RefreshBusEndpoint.busRefresh()"
  owner: "org.springframework.cloud.bus.endpoint.RefreshBusEndpoint"
  casEndpoint: false
- method: "POST"
  path: "busrefresh/${destinations}"
  name: "busrefresh"
  endpointType: "Endpoint"
  signature: "RefreshBusEndpoint.busRefreshWithDestination(java.lang.String[])"
  owner: "org.springframework.cloud.bus.endpoint.RefreshBusEndpoint"
  casEndpoint: false
  parameters:
  - required: true
    type: "String[]"
    selector: true
