---
- method: "GET"
  path: "jwtTicketSigningPublicKey"
  signature: "JwtTokenCipherSigningPublicKeyEndpoint.fetchPublicKey(java.lang.String) "
  owner: "org.apereo.cas.token.JwtTokenCipherSigningPublicKeyEndpoint"
  returnType: "String"
  casEndpoint: true
  summary: "Get public key for signing operations."
  parameters:
  - required: false
    type: "String"
    selector: false
    name: "service"
  produces:
  - "text/plain"
