---
- method: "GET"
  path: "throttles"
  signature: "ThrottledSubmissionHandlerEndpoint.getRecords()"
  owner: "org.apereo.cas.web.support.ThrottledSubmissionHandlerEndpoint"
  returnType: "List"
  casEndpoint: true
  summary: "Get throttled authentication records."
