---
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties"
  type: "java.lang.Boolean"
  description: "Flag to indicate whether successful password change should trigger\
    \ login automatically."
  name: "cas.authn.pm.auto-login"
  defaultValue: false
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties"
  type: "java.lang.Boolean"
  description: "Indicates whether password management should activate captcha for\
    \ password reset ops, etc."
  name: "cas.authn.pm.captcha-enabled"
  defaultValue: false
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties"
  type: "java.lang.Boolean"
  description: "Flag to indicate if password management facility is enabled."
  name: "cas.authn.pm.enabled"
  defaultValue: false
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.ForgotUsernamePasswordManagementProperties"
  type: "java.lang.Boolean"
  description: "Indicates whether forgot-username feature should activate captcha\
    \ for ops that start the forgot-username flow."
  name: "cas.authn.pm.forgot-username.captcha-enabled"
  defaultValue: false
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordHistoryProperties"
  type: "java.lang.Boolean"
  description: "Flag to indicate if password history tracking is enabled."
  name: "cas.authn.pm.history.enabled"
  defaultValue: false
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties"
  type: "java.util.List<org.apereo.cas.configuration.model.support.pm.LdapPasswordManagementProperties>"
  description: "Manage account passwords in LDAP."
  name: "cas.authn.pm.ldap"
  defaultValue: ""
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties"
  type: "java.lang.String"
  description: "A String value representing password policy regex pattern. <p> Minimum\
    \ 8 and Maximum 10 characters at least 1 Uppercase Alphabet, 1 Lowercase Alphabet,\
    \ 1 Number and 1 Special Character."
  name: "cas.authn.pm.policy-pattern"
  defaultValue: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[$@$!%*?&])[A-Za-z\\d$@$!%*?&]{8,10}"
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties.Reset"
  type: "java.lang.Long"
  description: "How long in minutes should the password expiration link remain valid."
  name: "cas.authn.pm.reset.expiration-minutes"
  defaultValue: 1
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties.Reset"
  type: "java.lang.Boolean"
  description: "Whether the Password Management Token will contain the client IP Address."
  name: "cas.authn.pm.reset.include-client-ip-address"
  defaultValue: true
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties.Reset"
  type: "java.lang.Boolean"
  description: "Whether the Password Management Token will contain the server IP Address."
  name: "cas.authn.pm.reset.include-server-ip-address"
  defaultValue: true
- module: "cas-server-support-pm-webflow"
  owner: "org.apereo.cas.configuration.model.support.pm.PasswordManagementProperties.Reset"
  type: "java.lang.Boolean"
  description: "Whether reset operations require security questions, or should they\
    \ be marked as optional."
  name: "cas.authn.pm.reset.security-questions-enabled"
  defaultValue: true
