---
- module: "cas-server-support-reports"
  owner: "org.apereo.cas.configuration.model.core.monitor.ActuatorEndpointProperties"
  type: "java.util.List<EndpointAccessLevel>"
  description: "Define the security access level of the endpoint.\nAvailable values:\n\
    \ {@code PERMIT}:Allow open access to the endpoint. {@code ANONYMOUS}:Allow anonymous\
    \ access to the endpoint. {@code DENY}:Block access to the endpoint. {@code AUTHENTICATED}:Require\
    \ authenticated access to the endpoint. {@code ROLE}:Require authenticated access\
    \ to the endpoint along with a role requirement. {@code AUTHORITY}:Require authenticated\
    \ access to the endpoint along with an authority requirement. {@code IP_ADDRESS}:Require\
    \ authenticated access to the endpoint using a collection of IP addresses."
  name: "cas.monitor.endpoints.endpoint.access"
  defaultValue: ""
- module: "cas-server-support-reports"
  owner: "org.apereo.cas.configuration.model.core.monitor.ActuatorEndpointProperties"
  type: "java.util.List<String>"
  description: "Required user authorities."
  name: "cas.monitor.endpoints.endpoint.required-authorities"
  defaultValue: ""
- module: "cas-server-support-reports"
  owner: "org.apereo.cas.configuration.model.core.monitor.ActuatorEndpointProperties"
  type: "java.util.List<String>"
  description: "Required ip addresses."
  name: "cas.monitor.endpoints.endpoint.required-ip-addresses"
  defaultValue: ""
- module: "cas-server-support-reports"
  owner: "org.apereo.cas.configuration.model.core.monitor.ActuatorEndpointProperties"
  type: "java.util.List<String>"
  description: "Required user roles."
  name: "cas.monitor.endpoints.endpoint.required-roles"
  defaultValue: ""
- module: "cas-server-support-reports"
  owner: "org.apereo.cas.configuration.model.core.monitor.ActuatorEndpointsMonitorProperties"
  type: "java.lang.Boolean"
  description: "Control whether access to endpoints can be controlled via form-based\
    \ login over the web via a special admin login endpoint."
  name: "cas.monitor.endpoints.form-login-enabled"
  defaultValue: false
